<?define ('wwwf_IN',true);
$title = "Abortion and Market Failure Theory";
$desc = "Books/papers on free market economics and policy, pro-life policy, Cobin CV, links, photos, other resources, allodial title, fire safety regulation, building regulation, free market policy, drug legalization, abortion debate";
$key = "allodial title, allodialism, allodial policy, free market textbook, homeschool books, economics books for homeschoolers, public policy and Christians, creation and evolution, Christian homeschool books, public policy books, pro-life books, abortion issue, Christians and government, building regulation, allodial title, tax protesting, revolution, fire safety regulation, accreditation of higher education, public choice economics, Virginia school, Austrian economics, law and economics, subjectivist economics, knowledge problem, market failure, government failure, urban regulation, fire safety regulation, romantic vision of government, public, choice, Austrian, economics, law, rent seeking, right, allodial, regulation, policy, vote, government, Bible, pro-life, Christian, building, zoning, liberty, planning, market, Chile, abortion debate, public school, Romans 13, feudal, privatization, allodial property";
$alt = "Policy of Liberty is your source for books/papers on free market economics and pro-life policy as well as quotes and links to economic related issues";
$titleimg = "papers.jpg";include ("top.php")?>
<TABLE cellpadding="0" cellspacing="0" border="0" width="771" height="240">
<tr><td rowspan="2"><IMG height="240" alt="<? echo "$alt"?>" src="images/paper.jpg" width="359" border="0"></td>
<td valign="top"><p class="pl">Policy of liberty is dedicated to the advancement of liberty and responsibility in society. Its philosophy is neither strictly libertarian nor strictly conservative, though strongly supporting the former in terms of economics and the latter on most social issues, abortion in particular. POL provides resources, links, books and articles, an email list, photos and links to famous economists, great quotations for liberty.</p></td></tr>
<tr><td width="409" bgcolor="#CCCCCC" height="90" border="2" align="right"></td></tr></TABLE>
<table cellpadding="0" cellspacing="0" width="771" border="0" bgcolor="#999999">
<tr><td><img src="white.gif" alt="<? echo "$alt"?>" height="3" width="771"></td></tr>
<tr><td><p class="white"><b>Abortion and Market Failure Theory:</b></p></td></TD></tr></table>
<br><table width="771"><tr><td><p class="head" align="center"><B>Abortion and Market Failure Theory</B></p>
<BR><P class="subhead" align="center">John Cobin, Ph.D.<br><p class="pl" align="center">Copyright &#169; 2000 by John Cobin</p>
<BR><br><P class="pl">A February 1998 <I>Liberty</I> poll found that 43% of respondents agreed with the proposition: &quot;abortion is wrong.&quot; Thus, we might conclude that pro-life sentiment exists within a substantial minority of classical liberals. Being one scholar within that minority, I would like to offer an explanation for this seemingly anomalous tendency, showing why it is consistent with classically liberal principles. Then I propose to embellish the notion by an economic analysis that might well be agreeable to people on both sides of the abortion issue. Indeed, I argue that the lion's share of abortions are the result of distortions caused by government failures, myopic intervention, and policies that facilitate deleterious rent seeking.</P>
<BR><P class="pl"><b>I. Classical Liberalism vs. Proactive Public Policy</b></P>
<BR><P class="pl">Classical liberalism exalts individual human rights. The idea espoused by abortion choicers (at least most scholarly ones that I know) is that human beings must first be endowed with a sacred grail called &quot;personhood&quot; before gaining full protection under the law. This status is granted upon being favorably inspected and approved by some social consensus or public policy. Only after receiving this blessing does the human being become a &quot;rights-bearing&quot; individual.</P>
<BR><P class="pl">However, from the pro-life perspective, this idea of having two classes of human beings runs contrary to consistently classically liberal thought, where the presumption is that living human beings are all persons and thus are rights bearers on account of their membership in the species. As Peter Kreeft has astutely shown, human beings are a sub-class of persons, not the other way around. Following historical precedent, we have always included other living entities besides humans among persons, e.g., God, extraterrestrials, angels, etc.</P>
<BR><P class="pl">Furthermore, our rights are not confirmed by public policy; they are antecedent to it. This perspective is the only one which can be said to be classically liberal. (Not suprisingly, 89% of respondents in the <i>Liberty</i> poll agreed with the statement: &quot;All men by their nature have a right to life&quot; and to &quot;liberty&quot; and 83% agreed that &quot;All men by their nature have a right to property&quot;.) If any public policy is legitimate it must be reactive rather than proactive, and certainly not entail granting the state or some coercive (or otherwise authoritative) communitarian pact to decide which of our species has rights and when. Alternatively, denying rights to certain classes of human beings on philosophical grounds has been a hallmark of leftists and criminals (if there is a difference between the two) for centuries. Their idea is simple: a few of us reason and decide that some class of human beings should be excluded from being rights-bearers and enforce our thesis via proactive public policy. The criteria used might be genetic, ethnic, superficial (e.g., skin color or size), or some arbitrarily picked point of development.</P>
<BR><P class="pl">Consistent with the classically liberal framework, I start with the simple assertion that (1) all living human beings have rights, (2) that their rights are antecedent to the state or &quot;natural&quot;, and that (3) they are shared equally by all living, innocent human beings without any discrimination favoring one over another for any reason. For me, this is the purest classically liberal view. Alternatively, the predominant view among Libertarian academics suggests that the  state or some social apparatus must first decide which human beings are qualified as &quot;persons&quot; and then grant them rights. Hence, rights are not natural but derived from the community or political process. After the linguistic and legal ruse that artificially divides humanity and personhood is accomplished, steps 1, 2 and 3 supra can be repeated by replacing the term &quot;human beings&quot; with the word &quot;persons&quot; and we have a policy-relevant rights theory. We also end up with a rationale for killing. Indeed, we can kill the non persons and demand protection for the rest who have qualified. For many, it is a means of having their cake and eating it too. However, I would like to emphasize that it is no minor offense to classical liberalism that public policy or some authoritative social apparatus has been injected into the rights-granting process (perhaps unwittingly) as the superior or grantor of rights. But such intervention is only the beginning of sorrows.</P>
<BR><P class="pl"><b>II. Market Failure Theory Analysis</b></P>
<BR><P class="pl">Unwanted pregnancies, in an economic sense, involve either crimes or negative externalities. That is, they result from rape on the one hand or, on the other hand, they are the unintended &quot;bad&quot; consequence of mutually beneficial exchanges. (Note that wanted pregnancies could well be a positive externality, depending on preferences and the circumstances.) Since something like 99.9% of all unwanted pregnancies fall into the negative externalities category, it is most useful to focus any policy discussion on them.</P>
<BR><P class="pl">As with all negative externalities, there are three (or more) parties involved: two people who exchange and have mutually beneficial gains from trade, and one person who incurs costs as a by-product of the production of the others-but who shares in none of the benefits from their transaction. When property rights are clearly defined, the parties who exchange must compensate those who would be damaged by their production that are not parties to the transaction. The parties exchanging often buy insurance that will compensate for any unintended damages. Thus, in one way or another, the social costs are internalized. However, when property rights are not well defined, i.e., when it is costless to pollute or to damage third parties (unintentionally), these social costs will not be internalized and third parties will lose. Such a scenario is deemed a &quot;market failure&quot; in the extant economics literature.</P>
<BR><P class="pl">There are a couple ways to deal with or &quot;solve&quot; market failures. One way has been outlined by Coase, et al. When transactions costs are very low (i.e., lower than litigation costs), and there is free bargaining, third parties will arrive at an agreement with those producing the damage without any government intervention, i.e., they will receive some compensation. However, when transactions costs are high, Coase's argument implies that government-made or judge-made policy may be able to alleviate the problem better than the market can. In sum, proactive public policy is thought to be able to improve on what the market produces or to alleviate the market's failure.</P>
<BR><P class="pl">Abortion involves a market failure. The adversely affected third party is the unborn child(ren). The transactions costs are very high for him to bargain because he cannot talk yet or write or bargain in any way. Yet this fact does not necessarily empower public policy to provide more optimal results than Coasean bargaining. The unborn child is a minor and, therefore, just a 5 year old minor who is damaged by soot from a factory, someone else from the human species may vouch for him as guardian and vicar. Plus, it is well established practice in law that this benefactor need not be his natural parents. Indeed, classical liberalism would have no qualms with anyone entering on a child's behalf in order to save or protect him. Logistically, guardianship may be purely contractual, where one auctions off the flow of utility for years of having a kid to the highest bidder. So then, the transactions costs are shifted to the guardian who becomes the unborn child's vicar, and his transactions costs of negotiating a settlement are far lower than the unborn child's would be. This outcome is not surprising. Markets automatically tend toward such cost-minimizing solutions.</P>
<BR><P class="pl">Thus, there is little reason to doubt that some agreement would be reached in the market to deal with unwanted pregnancies without resorting to public policy-especially given the evidence of a extensive network of people who dedicate their time to helping the unborn and the present high demand for adoption services. Adoption services compete with abortion services. They are two distinct solutions to the &quot;market failure&quot;. Abortion markets are largely artificial and inefficient, not to mention morally vile. On the other hand, there are many Coasean solutions to be found in the adoption market. Conformably, both Chicago and Virginia public choice theory would suggest that any intervention which precludes Coasean solutions would tend to make the abortion situation worse in terms of social efficiency.</P>
<BR><P class="pl">On the one hand, markets will never resolve the unwanted pregnancy problem perfectly but, over time, they would tend to provide the most efficient and effective allocation of productive resources, and create institutions and incentives that best maximize those goals and thus minimize abortions. In the market, ultimately, the number of abortions in society will depend on social pressures and individual preferences. Hence, absent the manipulation of information and encouragement of abortion solutions by government, it seems reasonable to conclude that preferences would not so strongly favor abortion. This makes some sense given that, at present, a mother's cost in terms of being responsible for her procreative actions is lower than it otherwise would be, since there is an socially accepted way &quot;out&quot; for her. In short, proactive public policy has artificially reduced her costs.</P>
<BR><P class="pl">On the other hand, government intervention to fix the alleged market failure tends to exacerbate the problem of unwanted pregnancies. Such proactive policies only tend to benefit rent seekers, viz., those who benefit from creating artificial scarcity. In the case of abortion, artificial scarcity is created for abortion services, fetal tissue harvests, etc. Surely, like legally mandated air bags and smoke detectors, there will always be a demand for abortion products, but rulings and legislation favoring abortion changes catallactic institutions and incentives. These changes permit special interest groups to capitalize on new opportunities by channeling more ill-directed funds to their faction. In short, people will demand far more abortion services than they would normally demand in the market on account of the policy designed to fix the market failure. Moreover, market-based institutions will also suffer. For instance, adoption is a market-based solution to the negative externality problem. It is no wonder that governments, which tend to coddle rent seekers, do their best to hinder this institution. They also make it difficult for babies to be positively priced in the market, which leads to other distortions.</P>
<BR><P class="pl">As a result, abortion policy yields social inefficiency and negative sum games. Abortion, the killing of innocent human beings, is not minimized. In fact, it is maximized/optimized and rent seekers benefit from it. Society loses because of (1) the reduction of human minds available, (2) the shift in labor from productive activities into rent seeking and humanity-destroying activities, (3) the monopoly prices consumers face via restrictions on certain output pertaining to the abortion industry or in &quot;buying&quot; a child via adoption, (4) the diversion of scarce resources from their normal productive uses into abortion prevention or promotion; just as devoting time and money to prevent burglary is a &quot;waste&quot; or non-productive, so preventing the killing of innocent human beings is a costly activity that channels resources from productive activity, and (5) the costs of &quot;paperwork contests&quot; that are generated as many rent seekers spend resources to obtain or retain the same booty which only one can win. Policymakers never had a chance to achieve their public benefit goals anyway, even if they really were publicly spirited, on account of the &quot;knowledge problem&quot; that they face (per Mises and Hayek). They cannot possibly garner sufficient social knowledge to improve on the market or correct its &quot;failure&quot;.</P>
<BR><P class="pl">The market indeed failed (at least in terms of producing zero unwanted pregnancies). That is bad or less than paradise. However, public policy creates a government failure which ends up being worse. We trade purgatory for hell. Furthermore, the rent seeking game worsens as regressive (rent seeking) entrepreneurs begin to &quot;alertly&quot; find arbitrage niches, like growing and harvesting fetal tissues. This again changes institutions and incentives and exacerbates the negative externality problem. Even if the number of abortions does not continue to rise perpetually, a distorted market equilibrium will be found which tends to make the number of abortions and unwanted pregnancies remain at a new, artificially high rate. On account of the institutional arrangements and ease of getting an abortion, mothers will have fewer incentives to avoid unwanted pregnancies. Then as institutions also develop to benefit the mother in a pecuniary manner, e.g., she might be paid for selling off pieces of her unborn child, abortion would become more permanent and attractive, and could tend to occur at later stages of gestation. The bottom line: many politicians are happy, rent seekers are happy, certain moral philosophers and feminists are elated; but most individuals in society suffer on account of this artificially extensive market.</P>
<BR><P class="pl"><b>III. Counting the Social Cost</b></P>
<BR><P class="pl">The greatest sufferers are, of course, those 40 million plus innocent unborn children who have been killed in the USA alone and the proximate millions that will be killed in ensuing years. Society loses minds and the ideas they would have, as well as the resources that are siphoned off in order to kill them, etc. But the murdered lose the opportunity to live and to enjoy life and all that living entails. Too, they have to bear the pain of being burned to death by saline solution or chopped up into pieces by sharp instruments, and would hardly be consoled by the fact that their remains will go to benefit medical science or rent seekers.</P>
<BR><P class="pl">In short, economic analysis suggests that abortion policy is not in the public interest-and no public policy can be justified which is not in the public interest. We already knew that from Julian Simon's thesis alone, which says that more minds bring some short term costs but far greater long term gains. The mind is the ultimate resource and the only thing which is truly scarce in absolute terms. Abortion thus adversely affects society by both reducing the quantity of minds available and by exacerbating negative externalities. Accordingly, I conclude that abortion is not in the public interest on account of both of these reasons and, therefore, it can not be a just or genuinely beneficial public policy. Abortion policy leads to negative sums game which, like other forms of murder or theft, only benefit some at the expense of others.</P>
<BR><P class="pl">In conclusion, abortion policy is an evil both morally and theoretically. It also stems from a philosophy of rights which is antagonistic to classically liberal principles. Nevertheless, I imagine that many of my adversaries among hard-core leftists or left-leaning Libertarians will reject my pro-life stance in general. But I hope that they will at least agree with me that state intervention supporting or promoting artificially high rates of abortion is simply deleterious.</P>
<BR><P class="pl"><b>IV. References</b></P>
<BR><P class="pl">Cobin, John M. (1999a), <a href="freemarket.php" class="pl"><I>A Primer on Modern Themes in Free Market Economics and Policy</I></a>, Parkland, Florida: Universal Publishers. http://www.PolicyOfLiberty.net/etextbook.html</P>
<BR><P class="pl">Cobin, John M. (1999b), <a href="books2.php" class="pl"><I>Pro-Life Policy: A Perspective for Liberty and Human Rights</I></a>, Trumann, Arkansas; Gemini Books.</P>
<br><P class="pl">Hayek, Friedrich A. von (1945), &quot;The Use of Knowledge in Society&quot;, <I>American Economic Review</I>, vol. 35, no. 4, September, pp. 519-530.</P>
<BR><P class="pl">Kreeft, Peter (1995), &quot;Human Personhood Begins at Conception&quot;, Castello Institute <a href="http://members.aol.com/pladvocate/person.html" class="linc">Medical Ethics Policy Monograph</a>, http://members.aol.com/pladvocate/person.html, Castello Institute of Stafford, Virginia.</P>
<BR><P class="pl"><I>Liberty</I> <a href="http://www.libertysoft.com/liberty/features/70libpoll.html" class="linc">Poll</a> (1998), <I>Liberty</I>, February.</P>
<BR><P class="pl">Simon, Julian (1996), <I>The Ultimate Resource 2</I>, Princeton, NJ: Princeton University Press.</P></td></tr></table><br>
<table cellpadding="0" cellspacing="0" width="771" border="0"><? include ("base.php")?>
