<?define ('wwwf_IN',true);
$title = "The Andean Altiplano: Lessons for the Mises-Tullock View of Development";
$desc = "Books/papers on free market economics and policy, pro-life policy, Cobin CV, links, photos, other resources, allodial title, fire safety regulation, building regulation, free market policy, drug legalization, abortion debate, etc...";
$key = "allodial title, allodialism, allodial policy, free market textbook, homeschool books, economics books for homeschoolers, public policy and Christians, creation and evolution, Christian homeschool books, public policy books, pro-life books, abortion issue, Christians and government, building regulation, allodial title, tax protesting, revolution, fire safety regulation, accreditation of higher education, public choice economics, Virginia school, Austrian economics, law and economics, subjectivist economics, knowledge problem, market failure, government failure, urban regulation, fire safety regulation, romantic vision of government, public, choice, Austrian, economics, law, rent seeking, right, allodial, regulation, policy, vote, government, Bible, pro-life, Christian, building, zoning, liberty, planning, market, Chile, abortion debate, public school, Romans 13, feudal, privatization, allodial property";
$alt = "Policy of Liberty is your source for books/papers on free market economics and pro-life policy as well as quotes and links to economic related issues";
$titleimg = "papers.jpg";include ("top.php")?>
<TABLE cellpadding="0" cellspacing="0" border="0" width="771" height="240">
<tr><td rowspan="2"><IMG height="240" alt="The Andean Altiplano: Lessons for the Mises-Tullock View of Development" src="images/paper.jpg" width="359" border="0"></td>
<td valign="top"><p class="pl">Policy of liberty is dedicated to the advancement of liberty and responsibility in society. Its philosophy is neither strictly libertarian nor strictly conservative, though strongly supporting the former in terms of economics and the latter on most social issues, abortion in particular. POL provides resources, links, books and articles, an email list, photos and links to famous economists, great quotations for liberty.</p></td></tr>
<tr><td width="409" bgcolor="#CCCCCC" height="90" border="2" align="right"></td></tr></TABLE>
<table cellpadding="0" cellspacing="0" width="771" border="0" bgcolor="#999999">
<tr><td><img src="white.gif" height="3" width="771" alt="<? echo "$alt"?>"></td></tr>
<tr><td><p class="white"><b>The Andean Altiplano: Lessons for the Mises-Tullock View of Development:</b></p></td></TD></tr></table>
<br><table width="771"><tr><td>
<p class="head" align="center"><B>The Andean Altiplano: Lessons for the Mises-Tullock View of Development</B></p>
<BR><P class="subhead" align="center">John Cobin, Ph.D.<br><p class="pl" align="center">Copyright &#169; 2000 by John Cobin</p>
<BR><br><P class="pl"><b>Introduction</b></P>
<BR><P class="pl">My recent trip to southern Perú, northwestern Bolivia, and the northeastern tip of Chile (areas of the Tiwanaku and Incan empires, roughly 1500BC to 1500AD) served to challenge my essentially Misesian-Tullockian view of culture and economic success.  These highlands, known as the Andean "Altiplano"; (or high plateau), provide a striking lesson in economic underdevelopment. Its countryside is majestic, and spectacularly verdant at times, safeguarded by protracted snowcapped peaks.  Its towns are quaint and rustic. Nonetheless, its indigenous or Indian population largely subsists in abject poverty, and its culture is conspicuously characterized by widespread Incan paganism.  Peru, Chile, and Bolivia are nominally Roman Catholic nations, although the Altiplano Indians (of Incan or Aymaran descent) either worship the gods of nature (i.e., the condor, the puma, the snake, etc.) or practice a religion which mixes the worship of these gods with traditional Catholic icons like Jesus, Mary, and the saints.</P>
<BR><br><P class="pl" align="center"><IMG SRC="gif/PlateauOverlookingSacredValleyIncas410x232.jpg" NAME="Graphic7" ALT="Verdant Plateau Overlooking the Sacred Valley of the Incas in Perú" ALIGN=BOTTOM WIDTH=410 HEIGHT=232 BORDER=0>
<BR><p class="smaller" align="center">February 13, 2000 <BR>A Verdant Plateau Overlooking the Sacred Valley of the Incas, Perú</P>
<BR><br><P class="pl">Intensifying this economic and cultural impression, shortly after visiting the Altiplano, I made an extensive excursion to the exquisitely beautiful island nations of New Zealand and Tahiti&#151;both of which are modern nations with much Protestant influence (at least historically).  These remote but developed islands&#151;New Zealand especially&#151;present a stark contrast with the Altiplano.  The Altiplano affords a heartrending example of what impoverishing feudalism must have wrought for so many centuries in Europe, where countless peasants were consigned to penury. </P>
<BR><br><P class="pl" align="center"><IMG SRC="gif/Andean/AucklandHarborOverlook323x250.jpg" NAME="Graphic8" ALT="Overview of Auckland, New Zealand's harbor and downtown from the Skytower" ALIGN=BOTTOM WIDTH=323 HEIGHT=250 BORDER=0><IMG SRC="gif/Andean/MooreaNorthShore273x250.jpg" NAME="Graphic9" ALT="Moorea Island (sister island of Tahiti) North Shore view" ALIGN=BOTTOM WIDTH=273 HEIGHT=250 BORDER=0>
<BR><p class="smaller" align="center">March 2000 <BR>Overview of Auckland, New Zealand's harbor and downtown from the Skytower<BR>Moorea Island (sister island of Tahiti) North Shore view</P>
<BR><br><P class="pl">The contrast stirred in my mind Max Weber's thesis: cultural matters have a significant influence on economic realities&#151;the Protestant work ethic in particular.  Moreover, the disparity seemed to demonstrate a flaw in the development thesis supplied by Ludwig von Mises and Gordon Tullock (i.e., predatory militarism and rent seeking) that I had come to accept. After all, New Zealand is a rent seeking society, even if less so now than before 1990s, and surely far more so than Peruvian, Bolivian, and even Chilean societies&#151;at least insofar as visible institutions are concerned (e.g., specialized ministries, regulations special interest groups, etc.).  Even more, Tahiti is a rent seeking colony subsidized by the French.  But the Altiplano region garners no such rents from any such political patrimony. </P> 
<BR><P class="pl">The contrast stirred in my mind Max Weber's thesis: cultural matters have a significant influence on economic realities&#151;the Protestant work ethic in particular.  Moreover, the disparity seemed to demonstrate a flaw in the development thesis supplied by Ludwig von Mises and Gordon Tullock (i.e., predatory militarism and rent seeking) that I had come to accept. After all, New Zealand is a rent seeking society, even if less so now than before 1990s, and surely far more so than Peruvian, Bolivian, and even Chilean societies&#151;at least insofar as visible institutions are concerned (e.g., specialized ministries, regulations special interest groups, etc.).  Even more, Tahiti is a rent seeking colony subsidized by the French.  But the Altiplano region garners no such rents from any such political patrimony. </P>
<br><br><P class="pl" align="center"><IMG SRC="gif/Andean/FlamingoLakeNEChile291x247.jpg" NAME="Graphic10" ALT="Flamingo preserve on Lake Chungará (elevation 15,060 ft./4,518 mt.&#151;the highest lake in the world) near the Parinacota volcano, Lauca National Park, northeastern tip of Chile" ALIGN=BOTTOM WIDTH=291 HEIGHT=247 BORDER=0><IMG SRC="gif/Andean/ChileBoliviaBorder193x223.jpg" NAME="Graphic11" ALT="Altiplano landscape, llamas and alpacas, with the Sajama volcano in the background, Bolivian-Chilean border (near Tambo, Bolivia)" ALIGN=BOTTOM WIDTH=193 HEIGHT=223 BORDER=0>
<BR><p class="smaller" align="center">February 2000<BR>Flamingo preserve on Lake Chungará (elevation 15,060 ft./4,518 mt.&#151;the highest lake in the world) near the Parinacota volcano, Lauca National Park, northeastern tip of Chile<BR>Altiplano landscape, llamas and alpacas, with the Sajama volcano in the background, Bolivian-Chilean border (near Tambo, Bolivia)</P>
<br><br><P class="pl">If development is inversely correlated with rent seeking and predatory militarism, why, then, do we find less developed areas (like the Altiplano) which feature no significant rent seeking or military predation?  Indeed, Altiplano wretchedness seems to confound the Mises-Tullock rationale for underdevelopment and, perhaps, indicate that cultural (i.e., religious) elements have had a far greater impact than modern scholars are willing to give them credit for. In this essay, I recapitulate some popular development theories proffered by economists, and I demonstrate the natural and unmistakable (yet widely overlooked) nexus between the development theories of Mises and Tullock.  Then, I convey some important details about modern Altiplano civilization. Beyond those elements, my purpose is to suggest a reformulation and improvement of the Mises-Tullock perspective by fusing it somewhat with the Weberian paradigm. </P>
<br><br><P class="pl" align="center"><IMG SRC="gif/Andean/MapAndeanAltiplano259x236.jpg" NAME="Graphic28" ALT="Map of the Andean Altiplano (area of the former Tiwanaku and Incan empires)" ALIGN=BOTTOM WIDTH=259 HEIGHT=236 BORDER=0>
<BR><p class="smaller" align="center">Map of the Andean Altiplano<BR>(area of the former Tiwanaku and Incan empires)</P>
<br><br><P class="pl"><br><b>Key theories of societal underdevelopment and backwardness</b></P>
<P class="pl">Many economists today propose one of three main theories about underdevelopment.  These include (1) the climate of a country, (2) the culture or religion of a country, especially considering the thesis of Weber in <a href="http://www.asahi-net.or.jp/~hw8m-mrkm/weber/world/ethic/pro_eth_frame.html" class="pl"> <i>The Protestant Ethic and the Spirit of Capitalism</i></a>, or (3) Tullock's thesis about the amount of rent seeking that exists in a country (Cobin 1999, p. 58).  To this third theory I append Mises's thesis about "predatory militarism"; in <a href="http://www.mises.org/humanaction/chap18sec4.asp" class="pl"> <i>Human Action: A Treatise on Economics</i></a> (pages 499-501), which likewise indicts the state as the chief cause of underdevelopment. Mises blames government's bellicose activism (or "predatory militarism";), interventionism, and the breakdown of the rule of law (along with the erosion of security of property rights) as the cause of underdevelopment.  This theme, I hope to demonstrate, is completely congruent with Tullock's government failure argument. </P>
<P class="pl"><i>Climate</i></P>
<p class="pl">Some economists argue that developed countries are situated in colder climates where people have had more incentive to work hard to produce and then to save some of their production (in order to survive during the wintertime).  I remember first encountering this thesis in a graduate microeconomics at George Mason University&#151;taught by renowned UCLA-spawned economist Walter Williams (cf. another UCLA professor, Diamond 1999).  People in warm tropical regions do not face the same dire circumstances, being able to live with far less shelter and clothing, and having an abundant year-round food supply.  Thus they tend to advance and produce less than other societies.  Of course, there are some notable exceptions to this thesis, namely tropical cities Hong Kong, Singapore, Taipei, Honolulu, and, perhaps, Sao Paulo and Papeete.  One might also point to thriving subtropical places like Bahrain, Brisbane, Johannesburg, and Miami as counterexamples. </P>
<br><br><P ALIGN="CENTER" class="pl"><IMG SRC="gif/19.gif" NAME="Graphic2" ALT="Walter Williams" ALIGN=BOTTOM WIDTH=165 HEIGHT=192 BORDER=0>
<BR><P ALIGN="CENTER" class="smaller">Walter E. Williams (1936- )</P>
<br><br><p class="pl">The Peruvian and Bolivian Altiplano is entirely tropical, but its high altitude, ranging from 9,000 feet to 15,000 feet above sea level, makes its climate far different than tropical lowlands or islands.  It is a mostly treeless region of endless rocky mountains and sometimes verdant valleys.  The growing season is short, and there are few crops which can be cultivated successfully.  Even though there is often little snowfall in the valleys, most of the year is inconsolably cold and quite windy.  Thus, even though tropical, the Altiplano hardly fits the typical notion of the climate theory of development.  In fact, the mixture of cold climate and abject poverty in the region seems to contradict its thesis.  In short, the cold climate of the Altiplano region has done nothing to spur its development. </P>
<P class="pl"><i>Weber's Protestant ethic idea</i></P>
<p class="pl">Weber's <a href="http://www.asahi-net.or.jp/~hw8m-mrkm/weber/world/ethic/pro_eth_frame.html" class="pl"> <i>The Protestant Ethic and the Spirit of Capitalism</i></a> provides a remarkable thesis about economic development.  He suggests that development is not just a function of free market capitalism but also of the specific ethic associated derived from Protestant religious conviction.  Considering that the vast majority of developed nations were historically Protestant, Japan being the notable exception, Weber's thesis is certainly plausible. </P>
<br><br><P ALIGN="CENTER" class="pl"><IMG SRC="gif/Andean/MaxWeber.jpg" NAME="Graphic6" ALT="Max Weber" ALIGN=BOTTOM WIDTH=200 HEIGHT=250 BORDER=0><BR>
<P ALIGN="CENTER" class="smaller">Max Weber (1864-1920)</P>
<br><br><p class="pl">Roman Catholics, observed Weber, lagged behind Protestants (Calvinists in particular) in industry. Protestants "both as ruling classes and as ruled, both as majority and as minority, have shown a special tendency to develop economic rationalism which cannot be observed to the same extent among Catholics either in the one situation or in the other. Thus the principal explanation of this difference must be sought in the permanent intrinsic character of their religious beliefs, and not only in their temporary external historico-political situations"; (Weber 1958 [<a href="http://www.asahi-net.or.jp/~hw8m-mrkm/weber/world/ethic/pro_eth_frame.html" class="pl">online</a>], chapter 1, paragraph 5). </P>
<p class="pl">Weber continues: "Montesquieu says (<a href="http://www.constitution.org/cm/sol.htm" class="pl"><i>The Spirit of Laws</i></a>, Book XX, chap. 7) of the English that they 'had progressed the farthest of all peoples of the world in three important things: in piety, in commerce, and in freedom'. Is it not possible that their commercial superiority and their adaptation to free political institutions are connected in some way with that record of piety which Montesquieu ascribes to them?"; (Weber 1958 [<a href="http://www.asahi-net.or.jp/~hw8m-mrkm/weber/world/ethic/pro_eth_frame.html" class="pl">online</a>], chapter 1, paragraph 10) </P>
<p class="pl">Weber saw an "idea of calling"; among Protestants that drove them to industry. They saw their "task"; in life as a calling from God, and capitalism "is rationalized on the basis of rigorous calculation, directed with foresight and caution toward the economic success which is sought in sharp contrast to the hand-to-mouth existence of the peasant, and to the privileged traditionalism of the guild craftsman and of the adventurers' capitalism, oriented to the exploitation of political opportunities and irrational speculation."; He adds that the Catholic nations of southern Europe were profoundly influenced by a different form of rationalism (which has led to different economic results) than the "irrational"; form which characterizes historically Protestant nations (irrational "from the standpoint of purely eudamonistic self-interest";) (Weber 1958 [<a href="http://www.asahi-net.or.jp/~hw8m-mrkm/weber/world/ethic/pro_eth_frame.html" class="pl">online</a>], chapter 2, last 2 paragraphs)."; </P>
<p class="pl">Weber noticed that Calvinistic Protestants pay more attention to life in this world than Catholics and Lutherans do. "One feels at once that this powerful expression of the Puritan's serious attention to this world, his acceptance of his life in the world as a task, could not possibly have come from the pen of a medieval writer. But it is just as uncongenial to Lutheranism, as expressed for instance in Luther's and Paul Gerhard's chorales (Weber 1958 [<a href="http://www.asahi-net.or.jp/~hw8m-mrkm/weber/world/ethic/pro_eth_frame.html" class="pl">online</a>], chapter 3, paragraph 15)."; </P>
<p class="pl">In America, Weber suggests, the Protestant ethic has reached its most developed form, as Benjamin Franklin points out the "supposed confession of faith of the Yankee";.  He cites Ferdinand Kürnberger, who "satirizes in his clever and malicious Picture of American Culture"; that the philosophy of Americans is to "make tallow [animal fat from which candles and soap were made] out of cattle and money out of men";. Weber suggests that there is a teleological component in this sentiment.  "The peculiarity of this philosophy of avarice appears to be the ideal of the honest man of recognized credit, and above all the idea of a duty of the individual toward the increase of his capital, which is assumed as an end in itself. Truly what is here preached is not simply a means of making one's way in the world, but a peculiar ethic. The infraction of its rules is treated not as foolishness but as forgetfulness of duty. That is the essence of the matter. It is not mere business astuteness, that sort of thing is common enough, it is an ethos."; Weber argues that this perspective has the "character of an ethically coloured maxim for the conduct of life"; which has only taken root in Western Europe and America. "Capitalism existed in China, India, Babylon, in the classic world, and in the Middle Ages. But in all these cases, as we shall see, this particular ethos was lacking."; (Weber 1958 [<a href="http://www.asahi-net.or.jp/~hw8m-mrkm/weber/world/ethic/pro_eth_frame.html" class="linc">online</a>], chapter 2, paragraphs 17 and 18) </P>
<p class="pl">For Weber, then, development is a function of not only capitalism and a stable legal framework wherein it may operate, but also of the Protestant work ethic.  By extension, the non Protestant Indians in the Peruvian and Bolivian Altiplano may have capitalism, but they will still not develop because the lack this essential ethic. </P>
<p class="pl">Weber, of course, is not without his detractors.  Rueven Brenner contends that Weber overlooked some key events in prosperous cities like Amsterdam.  Brenner argues that many educated and ambitious immigrants, notably French Huguenots, arrived in Amsterdam which in turn led to economic prosperity.  It had little to do with the Protestant ethic, he says, just as religion "was not a factor"; in Hamburg, Hong Kong, Singapore, Taiwan, and West Germany's development. Notably, all of those places, like Amsterdam, had liberal immigration policies (Brenner 1998). But there is little or nothing standing in the way of immigrants proposing to move to the Altiplano.  Accordingly, having an open immigration policy <i>in and of itself</i> does not yield prosperity.  Should the Altiplano region's misery, then, be blamed on a lack of proactive policies to encourage more immigration, like paying people to move there?  Amsterdam, Hamburg, and Hong Kong had something to offer immigrants, but the Altiplano apparently leaves something to be desired.  What policy could possibly fix that fact?  Brenner's thesis simply does not trump Weber's in the Altiplano case. </P>
<P class="pl"><i>Tullock's rent seeking explanation</i></P>
<p class="pl">Tullock has defined <i>rent seeking</i> as "the manipulation of democratic [or other types of] governments to obtain special privileges under circumstances where the people injured by the privileges are hurt more than the beneficiary gains"; (Tullock 1993, p. 24, cf. p. 51). James Buchanan says that "the term rent seeking is designed to describe behavior in institutional settings where individual efforts to maximize value generate social waste rather than social surplus"; (Buchanan 1980, pp. 46, 47). More precisely, every public policy leading to <i>legal involuntary transfers</i> is rent seeking, or is policy that in some way involves rent seeking activity, as noted in Table 1.  Thus, since all rent seeking produces negative sum games for society, it will tend to retard economic development too. Alternatively, it seems much less likely that any government policy involving voluntary exchange would retard development, since all voluntary catallactic activity results in positive sum games for both the game players and society.</P>
<br><br><P ALIGN=CENTER class="pl"><b>Table 1: Taxonomy of economic exchange</b>
<BR><BR><CENTER><TABLE WIDTH=403 BORDER=3 BORDERCOLOR="#000000" CELLPADDING=4 CELLSPACING=1>
<TR><TD WIDTH=151 BGCOLOR="#ccffcc"><P ALIGN=LEFT class="pl"><B>Economic Exchange</B></P></TD>
<TD WIDTH=111 BGCOLOR="#ccffcc"><P ALIGN=CENTER class="pl"><I><B>Legal</B></I></P></TD>
<TD WIDTH=107 BGCOLOR="#ccffcc"><P ALIGN=CENTER class="pl"><I><B>Illegal</B></I></P></TD></TR>
<TR><TD WIDTH=151 BGCOLOR="#ccffcc"><P ALIGN=LEFT class="pl"><I><B>Voluntary</B></I></P></TD>
<TD WIDTH=111 BGCOLOR="#cccccc"><P ALIGN=CENTER class="pl">Market</P></TD>
<TD WIDTH=107 BGCOLOR="#cccccc"><P ALIGN=CENTER class="pl">Black Market</P></TD></TR>
<TR><TD WIDTH=151 BGCOLOR="#ccffcc"><P ALIGN=LEFT class="pl"><I><B>Involuntary</B></I></P></TD>
<TD WIDTH=111 BGCOLOR="#cccccc"><P ALIGN=CENTER class="pl">Rent Seeking</P></TD>
<TD WIDTH=107 BGCOLOR="#cccccc"><P ALIGN=CENTER class="pl">Theft</P></TD></TR></TABLE></CENTER></p>
<br><br><p class="pl">For Tullock, both the climatic and cultural (i.e., religious) explanations of development are trumped by the industrious, non-Protestant Chinese and certain Africans.  Through his experience visiting China, seeing how its government operated, and then observing how Chinese and African immigrants fare in America, Tullock argues that development depends on how free a society is from rent seeking and other institutional distortions.  Thus, Tullock provides a rationale for why, for instance, Chinese people in tropical and much freer culturally Chinese cities like Hong Kong, Taipei, Singapore, plus multicultural countries like America, England, and Canada, do better economically than their counterparts in China. </P>
<br><br><P ALIGN=CENTER class="pl"><IMG SRC="gif/03.gif" NAME="Graphic4" ALT="Gordon Tullock" ALIGN=BOTTOM WIDTH=231 HEIGHT=327 BORDER=0>
<BR><p class="smaller" align="center">Gordon Tullock (1922- )</P>
<br><br><p class="pl">Tullock explains: "The <i>émigré</i> Chinese of southeast Asia and the United States perform extremely well, as do the <i>émigré</i> Indians of Africa.  Only in their own homelands do they fail to perform well.  The phenomenon is not peculiar to Chinese, Indian, or Islamic cultures, but rather is located in the traditional government institutions of these various backward societies.  Rent seeking offers a powerful general explanation of this apparent paradox.  It is not surprising that our common exposure to economic failure in culturally-advanced societies led Krueger, Bhagwati and myself to the rent-seeking explanation"; (Tullock 1993, pp. 20-21). </P>
<p class="pl">Thus, when a rent seeking society retards economic development, it forces a society to remain backwards.  It is not only militarism which causes underdevelopment, but rather the state institutions which retard growth, and foster corruption and privilege seeking. Civilian, privilege-dealing governments have been among the most terrible in history, notably those led by Lenin, Stalin, Lincoln, Mussolini, and Hitler.</P>
<br><br><P ALIGN=CENTER class="pl"><IMG SRC="gif/08.gif" NAME="Graphic9" ALT="James Buchanan" ALIGN=BOTTOM WIDTH=150 HEIGHT=150 BORDER=0><BR>
<p class="smaller" align="center">James Buchanan (1919- )</P>
<br><br><p class="pl">Conformably, in their book <i>The Capitalist Revolution in Latin America</i> (1997), Paul Craig Roberts and Karen Araujo have strongly argued that underdevelopment in Latin American countries has been caused by (or at least exacerbated by) rent seeking and bad public policies. Policies that compromise property rights can be particularly harmful, magnifying underdevelopment problems.  As Richard Pipes notes in <i>Property and Freedom</i>, there is a "symbiotic relationship between property and freedom"; (Pipes 1999, p. 287). Communist and fascist upheavals during the twentieth century, spawned by Leftist ideology unfavorable to private property (and political freedom), have left a legacy of underdevelopment around the world (pp. 209-225).  Alternatively, strong property rights policy, which of necessity implies both economic and political freedom, as well as the rule of law, foments economic development.  Accordingly, a comprehensive taxonomy of economic development may be derived, as noted in Table 2.</P>
<br><br><P ALIGN=CENTER class="pl"><b>Table 2: Taxonomy of economic development</b><BR><BR>
<CENTER><TABLE WIDTH="547" BORDER="3" BORDERCOLOR="#000000" CELLPADDING="4" CELLSPACING="3">
<TR><TD WIDTH=178 BGCOLOR="#ccffcc"><P ALIGN=LEFT class="pl"><B>Development Criteria</B></P></TD>
<TD WIDTH=167 BGCOLOR="#ccffcc"><P ALIGN=CENTER class="pl"><I><B>Weak Rent Seeking</B></I></P></TD>
<TD WIDTH=161 BGCOLOR="#ccffcc"><P ALIGN=CENTER class="pl"><I><B>Strong Rent Seeking</B></I></P></TD></TR>
<TR><TD WIDTH=178 BGCOLOR="#ccffcc"><P ALIGN=LEFT class="pl"><I><B>Strong Property Rights</B></I></P></TD>
<TD WIDTH=167 BGCOLOR="#cccccc"><P ALIGN=CENTER class="pl">Strong Development</P></TD>
<TD WIDTH=161 BGCOLOR="#cccccc"><P ALIGN=CENTER class="pl">Underperformace</P></TD></TR>
<TR><TD WIDTH=178 BGCOLOR="#ccffcc"><P ALIGN=LEFT class="pl"><I><B>Weak Property Rights</B></I></P></TD>
<TD WIDTH=167 BGCOLOR="#cccccc"><P ALIGN=CENTER class="pl">Despotism and Paucity</P></TD>
<TD WIDTH=161 BGCOLOR="#cccccc"><P ALIGN=CENTER class="pl">Backwardness</P></TD></TR></TABLE></CENTER></p>
<br><br><P class="pl"><i>Mises's view about "predatory militarism"; in backwards nations</i></P>
<p class="pl">Although Mises predated the formal inauguration of rent seeking theory <i>a la</i> Tullock, <i>et al</i>, it is clear from his work that he both understood the concept and viewed it as having a substantial economic effect. Accordingly, without using the precise term, Mises describes the fundamental problem of rent seeking in <a href="http://www.mises.org/humanaction/chap18sec4.asp" class="pl"><i>Human Action: A Treatise on Economics</i></a> (Mises 1996, pp. 272-273): </P>
<br><br><P ALIGN="CENTER" class="pl"><IMG SRC="gif/01.gif" NAME="Graphic2" ALT="Ludwig von Mises A" ALIGN=BOTTOM WIDTH=117 HEIGHT=143 BORDER=0><IMG SRC="gif/02.gif" NAME="Graphic3" ALT="Ludwig von Mises B" ALIGN=BOTTOM WIDTH=123 HEIGHT=143 BORDER=0><BR>
<p class="smaller" align="center">Ludwig von Mises (1881-1973)</P>
<br><br><p class="pl">"In an unhampered market economy the capitalists and entrepreneurs cannot expect an advantage from bribing officeholders and politicians. On the other hand, the officeholders and politicians are not in a position to blackmail businessmen and to extort graft from them. In an interventionist country powerful pressure groups are intent upon securing for their members privileges at the expense of weaker groups and individuals. Then the businessmen may deem it expedient to protect themselves against discriminatory acts on the part of the executive officers and the legislature by bribery; once used to such methods, they may try to employ them in order to secure privileges for themselves. At any rate the fact that businessmen bribe politicians and officeholders and are blackmailed by such people does not indicate that they are supreme and rule the countries. It is those ruled&#151;and not the rulers&#151;who bribe and are paying tribute."; </P>
<p class="pl">Like Tullock, Mises viewed underdevelopment and backwardness as a function of government failure.  Some of the most important failures have been proactive policies of "predatory militarism."; In several long passages from <a href="http://www.mises.org/humanaction/chap18sec4.asp" class="pl"><i>Human Action: A Treatise on Economics</i></a>, Mises comments (excerpted from Mises 1996, pp. 497-501, bold emphasis added): </P>
<p class="pl">"The start which the peoples of the West have gained over the other peoples consists in the fact that they have long since created the political and institutional conditions required for a smooth and by and large uninterrupted progress of the process of larger-scale saving, capital accumulation, and investment. Thus, by the middle of the nineteenth century, they had already attained a state of well-being which far surpassed that of races and nations less successful in substituting the ideas of acquisitive capitalism for those of <b>predatory militarism</b>. Left alone and unaided by foreign capital these backward peoples would have needed much more time to improve their methods of production, transportation, and communication."; </P>
<p class="pl">"It is impossible to understand the course of world affairs and the development of the relations between West and East in the last centuries, if one does no comprehend the importance of this large-scale transfer of capital. The west has given to the East not only technological and therapeutical knowledge, but also the capital goods needed for an immediate practical application of this knowledge. These nations of Eastern Europe, Asia, and Africa have been able, thanks to the foreign capital imported, to reap the fruits of modern industry at an earlier date. They were to some extent relieved from the necessity of restricting their consumption in order to accumulate a sufficient stock of capital goods. This was the true nature of the alleged exploitation of the <b>backward nations</b> on the part of Western capitalism about which their nationalists and the Marxians lament. It was a fecundation of the economically backward nations by the wealth of the more advanced nations."; </P>
<p class="pl">"The benefits derived were mutual. What impelled the capitalists of the West to embark upon foreign investment was the demand on the part of the domestic consumers. Consumers asked for goods which could not be produced at all at home and for a cheapening of goods which could be produced at home only with rising costs. If the consumers of the capitalist West had behaved in a different way or if the institutional obstacles to capital export had proved insurmountable, no capital export would have occurred. There would have been more longitudinal expansion of domestic production instead of lateral expansion abroad."; </P>
<p class="pl">Mises then proceeds to reject the climactic or environmental explanations for underdevelopment, in favor of a paradigm which is remarkably similar to Tullock's.  Certainly, Mises emphasized the lack of respect for individual rights in China and Africa rather than institutional problems leading to increased rent seeking activity.  Mises does, however, point out institutional problems that led to the diminution of capital accumulation in China and Africa. </P>
<p class="pl">"Praxeology and economics are foreign to the issues raised by this controversy. But they must take precautionary measures lest they become implicated by partisan spirit in this clash of antagonistic ideas. If those fanatically rejecting the teachings of modern genetics were not entirely ignorant of economics, they would certainly try to turn the time-preference theory to their advantage. They would refer to the circumstance that the superiority of the Western nations consists merely in their having started earlier in endeavors to save and to accumulate capital goods. They would explain this temporal difference by accidental factors, the better opportunity offered by environment.";</P>
<p class="pl">"Against such possible misinterpretations one must emphasize the fact that the temporal head start gained by the Western nations was conditioned by ideological factors which cannot be reduced simply to the operation of environment. What is called human civilization has up to now been a progress from cooperation by virtue of hegemonic bonds to cooperation by virtue of contractual bonds. But while many races and peoples were arrested at an early stage of this movement, others kept on advancing. <b>The eminence of the Western nations consisted in the fact that they succeeded better in checking the spirit of predatory militarism</b> than the rest of mankind and that they thus brought forth the social institutions required for saving and investment on a broader scale. Even Marx did not contest the fact that private initiative and private ownership of the means of production were indispensable stages in the progress from primitive man's penury to the more satisfactory conditions of nineteenth-century Western Europe and North America. <b>What the East Indies, China, Japan, and the Mohammedan countries lacked were institutions for safeguarding the individual's rights</b>. The arbitrary administration of pashas, kadis, rajahs, mandarins, and daimios was not conducive to large-scale accumulation of capital. The legal guarantees effectively protecting the individual against expropriation and confiscation were the foundations upon which the unprecedented economic progress of the West came into flower. These laws were not an outgrowth of chance, historical accidents, and geographical environment. They were the product of reason.";</P>
<p class="pl">"We do not know what course the history of Asia and Africa would have taken if these peoples had been left alone. What happened was that some of these peoples were subject to European rule and others&#151;like China and Japan&#151;were <b>forced by the display of naval power to open their frontiers</b>. The achievements of Western industrialism came to them from abroad. They were ready to take advantage of the foreign capital lent to them and invested in their territories. But they were rather slow in the reception of the ideologies from which modern industrialism had sprung. Their assimilation to Western ways of life is superficial.";</P>
<p class="pl">"We are in the midst of a revolutionary process which will very soon do away with all  varieties of colonialism. This revolution is not limited to those countries which were subject to the rule of the British, the French and the Dutch. Even nations which without any infringement of their political sovereignty had profited from foreign capital are intent upon throwing off what they call the yoke of foreign capitalists. <b>They are expropriating the foreigners by various devices&#151;discriminatory taxation, repudiation of debts, undisguised confiscation, foreign exchange restrictions. We are on the eve of the complete Disintegration of the international capital market. The economic consequences of this event are obvious; its political repercussions are unpredictable</b>.";</P>
<p class="pl">"In order to appreciate the political consequences of the disintegration of the international capital market it is necessary to remember what effects were brought about by the internationalization of the capital market. Under the conditions of the later nineteenth century it did not matter whether or not a nation was prepared and equipped with the required capital in order to utilize adequately the natural resources of its territory. There was practically free access for everybody to every area's natural wealth. In searching for the most advantageous opportunities for investment capitalists and promoters were not stopped by national borderlines. As far as investment for the best possible utilization of the known natural resources was concerned, the greater part of the earth's surface could be considered as integrated into a uniform world-embracing market system. It is true that this result was attained in some areas, like the British and the Dutch East Indies and Malaya, only by colonial regimes and that autochthonous governments of these territories would probably not have created the institutional setting indispensable for the importation of capital. But Eastern and Southern Europe and the Western Hemisphere had of their own accord joined the community of the international capital market.";</P>
<p class="pl">"The Marxians were intent upon indicting foreign loans and investments for the lust for war, conquest, and colonial expansion. In fact the internationalization of the capital market, together with free trade and the freedom of migration, was instrumental in removing the economic incentives to war and conquest</b>. It on longer mattered for a man where the political boundaries of his country were drawn. The entrepreneur and the investor were not checked by them. Precisely those nations which in the age preceding the first World War were paramount in foreign lending and investment were committed to the ideas of peace-loving "decadent"; liberalism. Of the foremost aggressor nations Russia, Italy, and Japan were not capital exporters; they themselves needed foreign capital for the development of their own natural resources. Germany's imperialist adventures were not supported by its big business and finance."; </P>
<p class="pl">Like Tullock, Mises sees that bad or distortive ideas mainly stem from the academy, which in turn produce widespread rent seeking and theft in backwards countries. The Mises-Tullock nexus is clear. Both would admit that extensive rent seeking is the proximate culprit causing underdevelopment, while at the same time holding that the general political economic views that produce a rent seeking society are ultimately responsible.  In short, backwardness is a function of government failure, which can be seen in both its predatory militarism and rent seeking forms, but all government failures are ultimately the result of bad intellectual ideas made into policy.  Together, Mises and Tullock provide the <i>complete</i> government failure view of underdevelopment, as noted in Table 3.</P>
<br><br><P ALIGN=CENTER class="pl"><b>Table 3: Comprehensive (Mises-Tullock) taxonomy of economic development</B>
<BR><BR><CENTER><TABLE WIDTH=595 BORDER=3 BORDERCOLOR="#000000" CELLPADDING=4 CELLSPACING=3>
<TR><TD WIDTH=178 BGCOLOR="#ccffcc"><P ALIGN=LEFT class="pl"><B>Development Criteria</B></P></TD>
<TD WIDTH=191 BGCOLOR="#ccffcc"><P ALIGN=CENTER class="pl"><I><B>Little Government Failure</B></I></P></TD>
<TD WIDTH=185 BGCOLOR="#ccffcc"><P ALIGN=CENTER class="pl"><I><B>Much Government Failure</B></I></P></TD></TR>
<TR><TD WIDTH=178 BGCOLOR="#ccffcc"><P ALIGN=LEFT class="pl"><I><B>Strong Property Rights</B></I></P></TD>
<TD WIDTH=191 BGCOLOR="#cccccc"><P ALIGN=CENTER class="pl">Strong Development</P></TD>
<TD WIDTH=185 BGCOLOR="#cccccc"><P ALIGN=CENTER class="pl">Underperformace</P></TD></TR>
<TR><TD WIDTH=178 BGCOLOR="#ccffcc"><P ALIGN=LEFT class="pl"><I><B>Weak Property Rights</B></I></P></TD>
<TD WIDTH=191 BGCOLOR="#cccccc"><P ALIGN=CENTER class="pl">Despotism and Paucity</P></TD>
<TD WIDTH=185 BGCOLOR="#cccccc"><P ALIGN=CENTER class="pl">Backwardness</P></TD></TR></TABLE></CENTER></P>
<br><br><P class="pl"><br><b>A few details about Altiplano life, its poverty, and its indigenous culture</b>
<p class="pl">Perhaps the rule of law is not as strong in the Altiplano region (via its distant capital cities Lima, La Paz, and Santiago) as it is elsewhere.  Yet it is clear that Altiplano property rights are well defined.  Indeed, one of the most striking features of the Altiplano countryside are the countless stone fences which wrinkle its valleys and hillsides, apparently dividing Indian fields. Of course, this fact should not strike us as odd.  Primitive societies, similar to those in the Altiplano, have often had strong property rights, and these rights have been traditionally enforced by custom or religion (Brenner 1983, ch. 2). </P>
<br><br><P ALIGN=CENTER><IMG SRC="gif/Andean/LaPazBolivia302x217.jpg" NAME="Graphic12" ALT="La Paz, Bolivia view from downtown looking north" ALIGN=BOTTOM WIDTH=302 HEIGHT=217 BORDER=0>
<BR><P ALIGN=CENTER class="smaller">February 17, 2000<BR>La Paz, Bolivia view from downtown looking north</P>
<br><br><p class="pl">It appears that much farm labor is collective, but for some reason feudal property "rights"; remain strictly separated.  Like everywhere else, Altiplano inhabitants are not allodiaries.  The state owns many of the natural resources (i.e., minerals, water rights, subsoil, etc.), but this fact has not stopped other peoples elsewhere (as in Chile) from attaining economic success. Moreover, privatization is a widespread phenomenon in Perú, Bolivia, and Chile which, one would suppose, would increase economic opportunities in the Altiplano.  Yet it manifestly has not. </P>
<p class="pl">Given this scenario, Weber's argument could be of great consequence.  It may be, as he argues, that capitalism is a <i>necessary</i> but not a <i>sufficient</i> cause of economic development. Maybe a Protestant work ethic (or even a Japanese one as proxy) is required&#151;in addition to widespread political and economic freedom&#151;in order to produce economic success in backwards places like the Altiplano. If this thesis were true, The World Bank and IMF would do well to alter their policies and begin sponsoring Protestant (or even Japanese) missionaries to the Third World!  One thing is clear: even after centuries of undertaking to proliferate their values among the Altiplano Indians, both the Catholics and the pagans have had comparatively little impact on fomenting Altiplano progress.  This fact alone should give us reason to at least reconsider Weber's claim. </P>
<P class="pl"><i>Tiwanaku-Incan paganism in the Altiplano</i>
<p class="pl">Most of these Altiplano Indians are mixed (if not pure-blooded) descendants of the Tiwanaku (Aymaran) or Incan peoples, and live within a few hundred mile radius of Lake Titicaca.  The high elevation of the Altiplano "civilization"; is impressive. Andean mountain peaks shoot up to 21,000 feet all around the region&#151;chock full of choice minerals that could be exploited.  Trees are very scarce, but beautiful high meadows and fountains appear during the few rainy months, permitting llama and other animal herding. </P>
<br><br><P ALIGN=CENTER class="pl"><IMG SRC="http://www.PolicyOfLiberty.net/kids/KidsOllantaytambo435x277.jpg" NAME="Graphic25" ALT="Ancient sun temple and fortress ruins in Ollantaytambo, Perú (about 90 minutes from Cusco, Perú)" ALIGN=BOTTOM WIDTH=435 HEIGHT=277 BORDER=0>
<BR><P ALIGN=CENTER class="smaller">February 13, 2000<BR>Ancient sun temple and fortress ruins in Ollantaytambo, Perú (about 90 minutes from Cusco, Perú)</P>
<br><br><p class="pl">Nearly all of these people still worship the <i>Mama Pacha</i> (mother nature), not too unlike modern American new agers perhaps. They have a host of sacred animals like the condor, the puma, the snake (which are worshipped), plus the llama (which they sacrifice), and the sun and constellations (which are the focus of much religious sentiment in temples and many ceremonies).  The Incas sustained the brutal practice of human sacrifice, limited slavery, and other noxious public policies.  For instance, the Incas used to bash the skull of a child in order to achieve "harmony" with, and "protection" services from, the "mountain god" by means of a "pure" sacrificial victim (Reinhard 1998).  Our tour guide glossed over these trifles, pointing out how these noble savages sought and found an "equilibrium"; with nature via their pantheism, or polytheism, whereas the Spaniards and their Catholicism only wrought disequilibrium. </P>
<br><br><P ALIGN=CENTER class="pl"><IMG SRC="gif/Andean/IncanWallCuzco313x214.jpg" NAME="Graphic18" ALT="Tour guide explains how the Incas cut, transported, and fitted together perfectly these angular stone blocks in the outer wall of the Incan Qorichanca temple (sun temple) ruins in Cusco, Perú" ALIGN=BOTTOM WIDTH=313 HEIGHT=214 BORDER=0><IMG SRC="gif/Andean/IncanTempleCuzco410x274.jpg" NAME="Graphic19" ALT="David Cobin with his rain gear stands inside a ceremonial room (chamber of the princesses) of the Incan Qorichanca (sun) temple ruins in Cusco, Perú" ALIGN=BOTTOM WIDTH=410 HEIGHT=274 BORDER=0>
<BR><P ALIGN=CENTER class="smaller">February 10, 2000<BR>Tour guide explains how the Incas cut, transported, and fitted together perfectly these angular stone blocks in the outer wall of the Incan Qorichanca temple (sun temple) ruins in Cusco, Perú<BR>David Cobin (in his rain gear) stands inside a ceremonial room (chamber of the princesses) of the Incan Qorichanca (sun) temple ruins in Cusco, Perú</P>
<br><br><p class="pl">The Incas built large, fascinating temples with perfectly interconnecting, angular cut stones (which they dragged from miles away).  Many of these ruins are still present today, and some are still used for rituals. The Incas practiced their craft in these temples, in hope of finding a means to enhance agricultural production.  They marked solstices and seasons with special ceremonies, calculating the exact trajectory of sunrays, and fitting them through incredibly precise temple architecture: lattices, chasms, mirrors, and doorways. The Spanish, of course, destroyed (or at least desecrated) most of these temples, taking all the gold from them, and using the temples as foundations for Catholic basilicas in the region.  For the once great Incan people, gold had a religious value but no use as money.  Alternatively, and conspicuously, all developed societies have a history of gold money. </P>
<br><br><P ALIGN=CENTER class="pl"><IMG SRC="gif/Andean/GoldAltarArequipa263x376.jpg" NAME="Graphic13" ALT="Gold overlaid altar in a Catholic church in Arequipa, Perú" ALIGN=BOTTOM WIDTH=263 HEIGHT=376 BORDER=0>
<BR><P ALIGN=CENTER class="smaller">February 2000<BR>Gold overlaid altar in a Catholic church in Arequipa, Perú </P>
<br><br><P><i>The Roman Catholic synthesis with Tiwanaku-Incan paganism</i>
<p class="pl">The Roman Catholic Church in the former Tiwanaku and Incan empire is a hideous example of a mixture of (essentially) paganism and Catholicism, where the whole gamut of gods are worshipped.  Gold-laden altars and churches, replete with paintings and images that mix Catholicism with pagan icons, line the region.  Crucifixes have the sun on them, and other pagan symbols, to make them more palatable to the conquered culture. Biblical characters are painted with the dark skin tones of the Indians and clothed with Indian garb.  The Last Supper painting is redone with a local roasted guinea pig as the main course.  The whole biblical account is melded into an Indian context.  Plus, In order to placate the Mama Pacha in her bad moods, a special Jesus called "Lord of the tremors"; is represented by an image in many Altiplano Catholic churches.  People rely on him to protect them from earthquakes that commonly strike the region. The religious synthesis is profound indeed. </P>
<p class="pl">One of the tour guides summed up local religious sentiment as follows: "Half of the people in these parts still worship the gods of the Incas. The other half are Catholic, meaning that they worship all the Incan gods along with the Catholic saints, Mary, Jesus, <i>et al</i>.";  History shows that the Incan gods were comprised in large part by the Tiwanaku gods, which were adopted after the Incas conquered the Tiwanaku.  Carrying on this adoptive culture, when the Spanish conquered the Incas, and brought with them new gods, it was most convenient to simply add the new gods to the existing set rather than throw out the old gods (cf. Reinhard 1998).  Evidently, the Altiplano Roman Church has done little to resist the synthesis. </P>
<br><br><P ALIGN=CENTER class="pl"><IMG SRC="gif/Andean/MachuPicchuWall315x268.jpg" NAME="Graphic20" ALT="Tour guide discussing the structural form and use of this large room in Machu Picchu, Perú, noting that the perfectly constructed stones indicate that it was a sacred place for the pagans" ALIGN=BOTTOM WIDTH=315 HEIGHT=268 BORDER=0><IMG SRC="gif/Andean/MachuPicchuTemple389x274.jpg" NAME="Graphic21" ALT="Pagan temple in Machu Picchu, Perú (a three hour train and bus ride from Cusco, Perú), the most holy place for the Incan people" ALIGN=BOTTOM WIDTH=389 HEIGHT=274 BORDER=0>
<BR><P ALIGN=CENTER class="smaller">February 11, 2000<BR>Tour guide discussing the structural form and use of this large room in Machu Picchu, Perú, noting that the perfectly constructed stones indicate that it was a sacred place for the pagans<BR>Pagan temple in Machu Picchu, Perú (a three hour train and bus ride from Cusco, Perú), the most holy place for the Incan people</P>
<br><br><p class="pl">In addition to having a yearly llama sacrifice near a temple ruins near their "sacred valley";, some pagan Tiwanaku and Incan descendants in Cusco, Perú also burn incense to the snake god of the underworld in order to bring them good health or healing.  I witnessed the remnants (i.e., some smoking incense on an altar) of a recently completed ceremony.  In Arequipa, Perú, Indians rely on previously consecrated Peppertree seeds to give them economic luck&#151;far different than the Protestant ethic's prescription for economic success.  In short, the former Tiwanaku and Incan empires are flush with many pretty good pagans and a multitude of pretty bad Catholics. </P>
<br><br><P ALIGN=CENTER class="pl"><IMG SRC="gif/Andean/BreadOvenSacredValley229x380.jpg" NAME="Graphic17" ALT="Poor Altiplano people and tourists at a large bread and "empanada" oven in the famous Indian market at Pisaq, Perú, in the Sacred Valley of the Incas" ALIGN=BOTTOM WIDTH=229 HEIGHT=380 BORDER=0>
<BR><P ALIGN=CENTER class="smaller">February 13, 2000<BR>Poor Altiplano people and tourists at a large bread and "empanada" oven in the famous Indian market at Pisaq, Perú, in the Sacred Valley of the Incas</P>
<br><br><P class="pl"><i>Altiplano poverty</i></P>
<p class="pl">There are some beautiful new sections of major cities in the region, such as the southern part of La Paz and a few areas in Lima and Arequipa.  However, the former Tiwanaku and Incan empire is a temple-lined economic backwater&#151;a dolorous example of poverty and backwardness. With <i>average</i> incomes in Bolivia of about US$55 per month, and no more than twice that much in Perú, many people live in clay huts with straw roofs.  I watched many of them walking barefooted along dusty roads.  Some of the more productive Indians sit along sidewalks and sell crafts, clamoring at tourists who pass by.  Others trying to sell trinkets encroach groups from tour busses.  Some of their typical wares include tiny hand-painted pots or whistles, or miniature hand-carved stone idols. Each small item fetches about fourteen American cents (if one bargains well).  And the Indians happily trade what takes them hours to make for a pittance. </P>
<br><br><P ALIGN=CENTER class="pl"><IMG SRC="gif/Andean/TiwanakuCarvedIdolBolivia166x382.jpg" NAME="Graphic13" ALT="Carved idol at the Tiwanaku ruins near Tambillo, Bolivia (45 miles west of La Paz)" ALIGN=BOTTOM WIDTH=166 HEIGHT=382 BORDER=0><IMG SRC="gif/Andean/TiwanakuTempleBolivia381x257.jpg" NAME="Graphic14" ALT="Kalasasaya temple in the Tiwanaku ruins near Tambillo, Bolivia (45 miles west of La Paz)" ALIGN=BOTTOM WIDTH=381 HEIGHT=257 BORDER=0>
<BR><P ALIGN=CENTER class="smaller">February 2000<BR>Carved idol at the Tiwanaku ruins near Tambillo, Bolivia (45 miles west of La Paz)<BR>Kalasasaya temple in the Tiwanaku ruins near Tambillo, Bolivia (45 miles west of La Paz)</P>
<br><br><p class="pl">There is reason to believe that many Altiplano people are lazy.  How else could it be that a non oppressed people, living in a relatively free society, would perpetually remain in abject poverty?  Clearly, the Altiplano does not have a repressive society like Cuba.  Yet every tourist sees many beggars in the streets.  True, they will see many more craft and trinket salespeople, and many shopkeepers in the cities, but does that fact alone suggest that Indian indolence is not widespread?  Maybe Altiplano people are not generally lazy, but it is difficult for any casual observer to appreciate that reality (if it is true). Alternatively, one would expect to see more advancement via regional industry.  Or might there be other cultural problems which tend to keep the region underdeveloped (even supporting Weber's thesis)?  For instance, if an individual's economic advancement is perceived as having occurred at the expense of others, it would be viewed as negative and thus shunned.  This happened in mule-spinning operations in India during the late 19th and early 20th centuries (Clark 1987).  A collectivist and thus substandard cultural or religious ethic might not produce the success and development wrought by a Protestant ethic. </P>
<br><br><P ALIGN=CENTER class="pl"><IMG SRC="gif/Andean/SellingCraftsFloatingTiticaca243x188.jpg" NAME="Graphic15" ALT="On a floating island (made of bound reeds) near Puno, Perú on Lake Titicaca, a hopeful Uro (Indian) woman sells crafts and hand made textiles to visitors" ALIGN=BOTTOM WIDTH=243 HEIGHT=188 BORDER=0>  <IMG SRC="http://www.PolicyOfLiberty.net/kids/JoshUroHutLakeTiticaca430x274.jpg" NAME="Graphic23" ALT="Joshua Cobin next to some reed huts on a floating island (made of bound reeds) near Puno, Perú on Lake Titicaca" ALIGN=BOTTOM WIDTH=430 HEIGHT=274 BORDER=0>
<BR><P ALIGN=CENTER class="smaller">February 2000<BR>On a floating island (made of bound reeds) near Puno, Perú on Lake Titicaca, a hopeful Uro (Indian) woman sells crafts and hand made textiles to visitors<BR>Joshua Cobin next to some reed huts on a floating island (made of bound reeds) near Puno, Perú on Lake Titicaca</P>
<br><br><p class="pl">Some of the most pathetic poor live on floating reed islands on Lake Titicaca.  Situated on the Peruvian-Bolivian border (elevation 12,500 feet), the lake is large (3,200 square miles) and its waters are always cold, and quite contaminated near the larger towns situated on it (such as Puno, Perú). In this bracing, damp, and parasite-ridden environment many Indians subsist without shoes. Indeed, assessing their circumstances, the very idea of them fishing in, defecating in, and drinking from the lake becomes repulsive.  One would think that if rent seeking were a prominent feature in the surrounding states that these poor wretches could at least get others to provide shoes for them, or better quality roofing than reeds. Enthusiastic rent seekers simply do not live in such abject poverty.  Moreover, the lake dwellers are not the only ones to be seen in such a predicament.  There are thousands of mud huts dotting the Altiplano landscape. Frankly, one would have no more justification in claiming that these pitiable people are rent seekers than to claim that they are oppressed or obtuse. Such speculative claims are certainly not warranted by the observable evidence. </P>
<br><br><P ALIGN=CENTER class="pl"><IMG SRC="http://www.PolicyOfLiberty.net/kids/KidsTombsAncientIncasPeru434x269.jpg" NAME="Graphic26" ALT="Burial grounds of the Tiwanaku and Incan peoples about an hour west of Puno, Perú and Lake Titicaca, the Cobin kids are in front of a tower tomb of a pagan nobleman" ALIGN=BOTTOM WIDTH=434 HEIGHT=269 BORDER=0>
<BR><P ALIGN=CENTER class="smaller">February 14, 2000<BR>Burial grounds of the Tiwanaku and Incan peoples about an hour west of Puno, Perú and Lake Titicaca, the Cobin kids are in front of a tower tomb of a pagan nobleman</P>
<br><br><P><i>Migration of Altiplano people to larger cities</i></P>
<p class="pl">With little in the way of social services and hardly any "quality"; public education, the indigenous peoples have little hope.  Even if they could get to a larger city, somehow, the services available to them would be minimal.  Still, many leave the Altiplano, hoping to make a better life (Marina 1967, Mangin 1967 and 1973). </P>
<br><br><P ALIGN=CENTER class="pl"><IMG SRC="gif/Andean/CuscoGirlsCostumes248x249.jpg" NAME="Graphic14" ALT="Indian girls in traditional indigenous costumes, Cusco, Perú street scene (with Joshua Cobin)" ALIGN=BOTTOM WIDTH=248 HEIGHT=249 BORDER=0>
<BR><P ALIGN=CENTER class="smaller">February 13, 2000<BR>Indian girls in traditional indigenous costumes, Cusco, Perú street scene (with Joshua Cobin)</P>
<br><br><p class="pl">Many migrants form highly successfully squatter settlements.  William Marina points out that poor settlers are often bashed by the police for a while, until authorities simply give up&#151;overwhelmed by the numbers of migrants. Quite often, these settlements are bastions of entrepreneurship, with low rates of disease, crime, and with a high savings rate (Marina 1975 and 1977). However, they turn into squalor when government intervenes to "help"; the poor.  For that reason, many migrants who attain prosperity ask governments to stay out (Marina 1995). One side of Lima is full of millions of abjectly poor Indians, living with little food in make-shift shelters lacking proper sanitation and potable water.  La Paz faces similar problems, although on a much smaller scale (its population is about a sixth of Lima's). Daniel Litvin notes that in other parts of Latin America, these urban poor fall prey to "disease-causing pollutants"; and lack health services (Litvin 1998, p. S8). These conditions might suggest, therefore, that rent seeking and intervention do play a role among the indigenous that leave the Altiplano and migrate to large cities. Litvin agrees.  "Once settled, squatter communities usually start lobbying the local government for legal recognition. This is often a long and tortuous process which becomes tangled in corruption"; (Litvin 1998, pp. S8-S9).  But real rent seeking among migrated Indians does not mean that there is rent seeking by Indians in the Altiplano region. </P>
<p class="pl">Many remain in their Altiplano homes.  One of the most enterprising artisans that I saw in Perú worked for many hours&#151;maybe days&#151;to hand paint several pottery pieces, musical instruments, and a chess set.  I bought all of them for about eight American dollars.  If the Indians are receiving substantial subsidies, they were not noticeable to me.  Outside of the cities especially, one only sees a largely bartering and subsistence culture. </P>
<br><br><P ALIGN=CENTER class="pl"><IMG SRC="gif/Andean/ClayArtisanCusco261x184.jpg" NAME="Graphic16" ALT="Local artisan working in the atrium of the Municipal Palace museum (Cusco, Perú) who hand paints pottery pieces, wind instruments, chess sets, and other crafts, a many of which I bought for eight American dollars (Guilia Davis looks on)" ALIGN=BOTTOM WIDTH=261 HEIGHT=184 BORDER=0>
<BR><P ALIGN=CENTER class="smaller">February 2000<BR>Local artisan working in the atrium of the Municipal Palace museum (Cusco, Perú) who hand paints<BR>pottery pieces, wind instruments, chess sets, and other crafts, a many of which I bought for eight American dollars (Guilia Davis looks on)</P>
<br><br><P class="pl"><i>Rent seeking and vote seeking in the Altiplano region</i>
<p class="pl">Even though my visit was short, it seems plausible to me that religious values contribute to Altiplano poverty.  Not only did many of the rural people seem lethargic or even indolent, but they had no ambition to strive for success. Sure, many sell crafts, and many more make them.  But Weber might be right.  Even if the Altiplano people have a <i>functional</i> work ethic, they do not have an <i>effective</i> one.  They have property rights, and they have political freedom and capitalism, but they also have poverty.  There is no visible oppression or predatory militarism.  Might there be a Weberian or cultural explanation?  Or might there be some persistent government failure due to rent seeking? </P>
<p class="pl">Scholars now widely recognize that rent seeking is a natural and largely unavoidable by-product of democratic processes.  Accordingly, it must also exist in the Altiplano, just as it does in New Zealand, Tahiti, India, or the United States.  However, the extensiveness and pervasiveness of rent seeking activities differ widely, depending on institutional factors. </P>
<p class="pl">Given my experience, I would argue that rent seeking problems are nearly insignificant in the Altiplano. On the supply side, with average monthly incomes of US$55 to US$110 per month one can imagine that few politicians or bureaucrats bother to try to extract taxes from these poor people.  I witnessed a well-developed barter economy too, which would hinder any tax collection efforts substantially. On the demand side, there were no major public works evident, other than the few main highways (which remain unpaved in Bolivia).  Public schools and hospitals are low quality, and there are few, if any, fabulously wealthy indigenous people (I saw none). Other than some rather lame political demonstrations evidently done in (the vain) hope of obtaining government "favors";, like overruling an proposed increase in monthly tap water prices by fifty cents, how can there be significant rent seeking? </P>
<p class="pl">The same is true for vote seeking.  I do not know if many of those illiterate people vote (in spite of the fact that it is compulsory for those who register), or even care about politics.  Most of them speak only one or two Indian languages and struggle with Spanish as a third language. I did see one boy at the Peru-Bolivia border running around and asking tourists if he could shine their shoes in German, English, and Spanish.  This event was somewhat impressive. At least he knew ten words in five different languages, which is probably more than even an average New York City dweller can boast. </P>
<p class="pl">Perhaps some of these people do understand something of political promises and, given that their opportunity cost is so low, they may indeed vote for anyone who promises to increase their average incomes by a dollar or two per month. Or they might despair of politics, viewing elections as rigged and politicians as corrupt.  Nevertheless, many, if not most, Altiplano residents do not have potable water, not to mention electricity, phones, etc., and their incomes are still low after many years of voting. Their hygiene is pathetic and their ignorance and superstition is staggering.  What evidence is there that politicians have brought any real benefits to these people?  Surely if vote seeking were an important factor, any demagogue could easily exploit the penury and misery of the Altiplano to capture some votes, and then throw the Indians a bone or two after being elected.  However, given the relative size of the larger cities in Perú and Bolivia, and especially in Chile, it would seem that favoring this small group of people generously would be political suicide for a vote seeker.  Thus, I conclude that vote seeking is not a significant distortion. </P>
<p class="pl">Moreover, Mises may be right, in general, when he says that bellicose tribal practices and interventionism led to the penury and troubles faced by the pathetic masses throughout the ages.  However, it is simply not true in the case of the remnant of the Tiwanaku and Incan empires over the last 500 years.  The Altiplano people have been subdued and pacified. </P>
<br><br><P ALIGN=CENTER class="pl"><IMG SRC="gif/Andean/MachuPicchuTerrace385x236.jpg" NAME="Graphic22" ALT="One of the steep terraces of Machu Picchu, Perú where corn (mainly) was cultivated by the Incas, the temple worship partly focused on increasing crop yields.  The once mighty temple and fortress is now a ruins and its people have been subdued." ALIGN=BOTTOM WIDTH=385 HEIGHT=236 BORDER=0>
<BR><P ALIGN=CENTER class="smaller">February 11, 2000<BR>One of the steep terraces of Machu Picchu, Perú where corn (mainly) was cultivated by the Incas, the temple worship partly focused on increasing crop yields.<BR>The once mighty temple and fortress is now a ruins and its people have been subdued.</P>
<br><br><p class="pl">Maybe the Mises-Tullock view of economic success is right, or at least right in some or most cases, but the Altiplano region makes us at least stop and take notice of Weber's theory again.  Predatory militarism and exorbitant rent seeking just do not seem like plausible explanations, and vote seeking distortions seem unlikely as well. </P>
<P class="pl"><br><b>Support for a fusion of Mises-Tullock with Weber</b></P>
<p class="pl">Some scholars, such as James Bradford DeLong, favor Tullock's thesis while discarding Weber's as anachronistic. "The presence or absence of parasitic, development retarding government is, of course, a key factor in accounting for comparative economic growth performance.  And whatever the role played by the "Protestant ethic"; in past centuries, it is clear that if government performance in the future turns on cultural factors it will turn on other cultural factors.  Neither fast growing Japan, fast growing Italy, or fast growing Spain owes anything to the Reformation."; (DeLong 1989, p. 14) </P>
<p class="pl">DeLong is certainly right that Weber cannot explain development in all countries, notably Japan, but Weber does have a plausible explanation for most cases.  No development theory, in fact, has a perfect explanatory record, and Weber is as good or better than the rest in this regard.  The United States, Canada, Australia, New Zealand, and much of Western Europe have tremendous rent seeking societies and yet are developed.  All of these nations could be offered as exceptions to Tullock's thesis, but by and large congruent with Weber's. </P>
<p class="pl">Surely DeLong is right in pointing out that parasitic government is a "key factor"; in underdevelopment&#151;congruent with Tullock.  However, the Altiplano region cannot be considered tropically warm, Protestant, a rent seeking society, or afflicted by predatory militarism.  Consequently, Weber's explanation has an edge on the others for why the Altiplano remains underdeveloped.  Unless DeLong or others can point out some "other cultural factors"; in the Altiplano region, a Weberian religious defect explanation is entirely plausible.  The lack of a Protestant heritage might be the key factor underlying Altiplano underdevelopment. Indeed, economic historians have found evidence from other societies which would support such a conclusion. </P>
<p class="pl">William Lazonick takes an institutional and interest group perspective on development that lends support to the Tullock thesis.  "As <a href="http://www.utdallas.edu/~harpham/joseph.htm"> Schumpeter </a> demonstrated long ago, one cannot analyze the <i>development</i> of an economy simply by analyzing decision-making by managers who take constraints as given, however optimal their choices may be [Schumpeter 1939 and 1961].  Rather, one needs to analyze the development of the institutional structures that largely determine interregional and international differences in, among other things, factor prices and productivity as well as the role of interested individuals and groups, including managers, in accepting, modifying, or drastically altering these constraints over time"; (Lazonick 1981, p. 91).  He found evidence that managers tend to have "technical and organizational conservatism"; that make constraints highly rigid. (p. 104). </P>
<br><br><P ALIGN=CENTER class="pl"><IMG SRC="gif/Andean/Schumpeter.gif" NAME="Graphic1" ALT="Joseph A. Schumpeter A" ALIGN=BOTTOM WIDTH=95 HEIGHT=134 BORDER=0>   <IMG SRC="gif/Andean/SchumpeterSmall.jpg" NAME="Graphic5" ALT="Joseph A. Schumpeter B" ALIGN=BOTTOM WIDTH=66 HEIGHT=66 BORDER=0><BR>
<P ALIGN=CENTER class="smaller">Joseph A. Schumpeter (1883-1950) </P>
<br><br><p class="pl">Gregory Clark builds on Lazonick's thesis, adding a Weber-sympathetic twist.  He points out that the specific problems that lead to low productivity (and thus underdevelopment) have to do with culture and religion.  The major source of underdevelopment is the inefficiency of a poor country's labor rather than an inability to absorb modern technology. In 1910, Clark reports that Protestant New England textile mill workers performed as much work as six Greek, Indian, Japanese, or Chinese workers (Clark 1987, pp. 141, 166).  He argues that local labor inefficiencies caused a drag on production (p. 169) and "the effects of local environment or culture on the labor force [w]as the source of poor performance of textile mills in low-wage countries"; (p. 172).  Even when alimentation, housing and education were equalized (although literacy was not an important factor since the manual spinning task was "highly routine";), production did not improve, indicating that cultural and religious values were the key factors (pp. 165-166). </P>
<p class="pl">Unlike the Altiplano story, Chile has risen to be a regional economic leader.  Is it of no consequence that an astounding (for an ostensibly Catholic nation) sixteen percent of Chileans now profess to be practicing Protestants (Gutiérrez Garcia 1999, p. 20)?  There seems to be a strong correlation between post-1975 surge in Chilean Protestantism and the increase in Chilean economic success during the same period.  Of course, we must also note that most of Chile has a non-tropical climate (Santiago has a climate similar to Fresno, California), and that it is hardly a crass rent seeking society.  So the Chilean case does not prove Weber is right, but it certainly provides little reason to discard his view. </P>
<p class="pl">The same could be said for economically booming South Korea. It too had sixteen percent Protestants in 1990,  "the highest percentage of Christians of any country in East Asia or Southeast Asia, with the exception of the Philippines"; (Savada and Shaw 1990).  By 1999, the figure had evidently risen to twenty-four percent: "Today [1999] about one third of South Korea's 45 million people are Christian&#151;11 million Protestants and 3 million Roman Catholics"; (Kim 1999, p. 1).  Accordingly, the Chilean and Korean evidence adds further reason in favor of again amalgamating Weber in an overall development view. </P>
<P class="pl"><br><b>Conclusion</b></P>
<p class="pl">The detractions from Weber by DeLong, Brenner, and even Tullock are not very compelling given the Altiplano case.  Instead, I would suggest that a more eclectic view be adopted.  This view would generally accept the Mises-Tullock perspective, while leaving room for a Weberian explanation at times, especially when there is no clear-cut case of government failure.  The result view would seem to be more robust, with more explanatory power. Indeed, by leaving room for Weber, at least now and then, we attain a more comprehensive theory of development.  Otherwise, the Mises-Tullock thesis alone simply does not well explain Altiplano underdevelopment, where cultural and religious values seem to be the main culprits. </P>
<p class="pl">Furthermore, the resulting fusion of Mises-Tullock and Weber would be knit together by a common thread.  There may indeed be different <i>proximate</i> reasons for underdevelopment: predatory militarism, rent seeking, or lack of a Protestant ethic.  But there is only one <i>ultimate</i> cause of underdevelopment: the generation of bad ideas among intellectuals that are transmitted into adverse public policies. </P>
<P class="pl"><br><b>References</b></P>
<p class="pl">Brenner, Rueven (1983), <i>History&#151;the Human Gamble</i>, University of Chicago Press: Chicago. </P>
<p class="pl">Brenner, Reuven (1998), "The Causes of Economic Growth,"; <a href="http://www.cato.org/pubs/policy_report/pr-index.html" class="linc"><i>Cato Policy Report</i></a>, May/June 1998, vol. XX, no. 3, p. 1; <a href="http://www.elcato.org/lascausasdeldesecon_Brenner.htm" class="linc">published online in Spanish</a> is the March 17, 1998 summary of the essay presented to the <a href="http://www.elcato.org/desarrollo.htm" class="linc">Cato Global Economic Freedom Project</a>.</P>
<p class="pl">Buchanan, James M. (1980), "Rent Seeking and Profit Seeking,"; in James Buchanan, Robert Tollison, and Gordon Tullock, eds., <i>Toward a Theory of The Rent-Seeking Society</i>, Texas A & M University Press: College Station, Texas.</P>
<p class="pl">Clark, Gregory (1987), "Why Isn't the Whole World Developed? Lessons from the Cotton Mills,"; <i>Journal of Economic History</i>, vol. 47, no. 1, March, pp. 141-173. </P>
<p class="pl">Cobin, John M. (1999), <a href="http://www.PolicyOfLiberty.net/etextbook.html" class="linc"><i>A Primer on Modern Themes in Free Market Economics</i></a>, Universal Publishers: Parkland, Florida.</P>
<p class="pl">DeLong, James Bradford (1989), "<a href="http://econ161.berkeley.edu/pdf_files/Protestant_Ethic.pdf" class="linc">The 'Protestant Ethic' Revisited: A Twentieth Century Look</a>,"; <i>Fletcher Forum</i>, vol. 13, no. 2 (Summer), pp. 229-242. </P>
<p class="pl">Diamond, Jared (1999), <i>Guns, Germs, and Steel: The Fates of Human Societies</i>, W W Norton & Co.: New York.</P>
<p class="pl">Gutiérrez Garcia, Pamela (1999), "<a href="http://www.policyofliberty.net/kids/ArticuloEvangelicos.htm" class="linc">Evangélicos Insertan su Religión en la Clase Media: El 16% de los Creyentes Se Declara Parte de Este Credo</a>,"; <i>La Tercera</i> (Chilean daily paper), Monday, May 17, pp. 20ff, citing a  <a href="http://www.cepchile.cl/encuestas/jun98/encuestas.htm" class="linc">major study by Centro de Estudios Públicos</a> in Santiago, June 1998. </P>
<p class="pl">Kim. Andrew E. (1997), "<a href="http://www.kimsoft.com/1997/xhist.htm" class="pl">History of Christianity in Korea: From Its Troubled Beginning to Its Contemporary Success</a>,"; <i>Korea Overseas Information Service</i>, posted online. </P>
<p class="pl">Lazonick, William (1981), "Factor Costs and the Diffusion of Ring Spinning in Britain Prior to World War I";, <i>Quarterly Journal of Economics</i>, vol. 96, no. 1 (February), pp. 89-109. </P>
<p class="pl">Litvin, Daniel (1998), "Living dangerously. Unhealthy Squatters' Settlements in Such Places as Brazil, Argentina and India,"; <i>The Economist</i>, vol. 346, no. 8060 (March 21), pp. S8-S9. </P>
<p class="pl">Mangin, William (1970), <i>Peasants in Cities: Readings in the Anthropology of Urbanization</i>, Houghton Mifflin: Boston (Resources for the study of anthropology series). </P>
<p class="pl">Mangin, William (1962), "Squatter Settlements,"; <i>Scientific American</i>, vol. 217, no. 4 (October), pp. 21-29. </P>
<p class="pl">Marina, William (1995), "Latin American Political Economies in the 21st Century,"; in Proceedings of the Latin American Political Economies in the 21st Century conference, San José, Costa Rica, October.
<p class="pl">Marina, William (1977), "Inflation and the Disintegration of the Social Order,"; <a href="http://www.namebank.com/Financial/WorldMoney.html" class="linc"><i>World Money Analyst</i></a>, Hong Kong. </P>
<p class="pl">Marina, William (1975), "Surviving in the Interstices,"; <i>Reason</i>, vol. 7, no. 2 (June), pp. 64-69. </P>
<p class="pl">Marina, William (1967), "Turner, the Safety-Valve and Social Revolution,"; in Duane  Koenig, ed., <i>Essays in Honor of Charlton W. Tebeau</i>, University of Miami Press: Miami. </P>
<p class="pl">Mises, Ludwig von (1996/1949), <A href="http://www.mises.org/humanaction.asp" class="linc"> <i>Human Action: A Treatise on Economics</i></a>, Fourth Revised Edition, The Foundation for Economic Education: Irvington-on-Hudson, New York. </P>
<p class="pl">de Montesquieu, Charles de Secondat (1914), <a href="http://www.constitution.org/cm/sol.htm" class="linc"> <i>The Spirit of Laws</i></a>, translated by Thomas Nugent and J. V. Prichard, G. Bell & Sons, Ltd.: London. </P>
<p class="pl">Pipes, Richard (1999), <i>Property and Freedom</i>, Alfred A. Knopf: New York</P>
<p class="pl">Reinhard, Johan, <i>et al</i> (1998), "<a href="http://www.pbs.org/wgbh/nova/transcripts/2516frozen.html" class="linc">Ice Mummies: Frozen in Heaven</a>,"; <i>NOVA Broadcast Transcript</i>, no. 2516 (November 24), Public Broadcasting System.</P>
<p class="pl">Roberts, Paul Craig and Karen Araujo (1997), <i>The Capitalist Revolution in Latin America</i>, Oxford University Press: New York and London.</P>
<p class="pl">Savada, Andrea Matles and William Shaw, eds. (1990), <a href="http://lcweb2.loc.gov/frd/cs/krtoc.html" class="linc"><i>South Korea&#151;A Country Study</i></a> (<a href="http://lcweb2.loc.gov/frd/cs/cshome.html" class="linc">Library of Congress Country Studies Series</a>), Department of the Army: Washington, D.C. </P>
<p class="pl">Schumpeter, Joseph Alois (1939), <i>Business Cycles: A Theoretical, Historical, and Statistical Analysis of the Capitalist Process</i>, McGraw-Hill: New York and London. </P>
<p class="pl">Schumpeter, Joseph Alois (1961/1934), <i>The Theory of Economic Development: An Inquiry into Profits, Capital, Credit, Interest, and the Business Cycle</i>, (Harvard Economic Studies, vol. 46), translated by Redvers Opie, Harvard University Press: Cambridge, Mass. </P>
<p class="pl">de Soto, Hernando (1989), <i>The Other Path: The Invisible Revolution in the Third World</i>, translation of <i>El Otro Sendero</i> by June Abbot, Tauris: London. </P>
<p class="pl">Tullock, Gordon (1993), <i>Rent Seeking</i>, The Shaftesbury Papers, 2, Edward Elgar Publishers Co.: Brookfield, Vermont. </P>
<p class="pl">Weber, Max, <a href="http://www.asahi-net.or.jp/~hw8m-mrkm/weber/world/ethic/pro_eth_frame.html" class="linc"><i>The Protestant Ethic and the Spirit of Capitalism</i></a>, New York: Scribner's Press, 1958.</P></td></tr></table><br>
<table cellpadding="0" cellspacing="0" width="771" border="0"><? include ("base.php")?>
