<?define ('wwwf_IN',true);
$title = "Public Policy Books";
$desc = "Books/papers on free market economics and policy, pro-life policy, Cobin CV, links, photos, other resources, allodial title, fire safety regulation, building regulation, free market policy, drug legalization, abortion debate, etc...";
$key = "allodial title, allodialism, allodial policy, free market textbook, homeschool books, economics books for homeschoolers, public policy and Christians, creation and evolution, Christian homeschool books, public policy books, pro-life books, abortion issue, Christians and government, building regulation, allodial title, tax protesting, revolution, fire safety regulation, accreditation of higher education, public choice economics, Virginia school, Austrian economics, law and economics, subjectivist economics, knowledge problem, market failure, government failure, urban regulation, fire safety regulation, romantic vision of government, public, choice, Austrian, economics, law, rent seeking, right, allodial, regulation, policy, vote, government, Bible, pro-life, Christian, building, zoning, liberty, planning, market, Chile, abortion debate, public school, Romans 13, feudal, privatization, allodial property, divine right, theonomy, liberty of conscience, pacifism, anabaptist, divine right of kings, nations, nationalism, slavery, civic duty, rebellion, rulers, states, Nock, resistance, activist, reconstruction, illegal immigration, constitutionalist, libertarian, social security, welfare, proactive, preemptive, war, peace";
$alt = "Policy of Liberty is your source for books/papers on free market economics and pro-life policy as well as quotes and links to economic related issues";
$titleimg = "books.jpg";include ("top.php")?>
<TABLE cellpadding="0" cellspacing="0" border="0" width="771" height="240">
<tr><td rowspan="2"><IMG height="240" alt="<? echo "$alt"?>" src="images/book.jpg" width="359" border="0"></td>
<td valign="top"><p class="pl">Policy of liberty is dedicated to the advancement of liberty and responsibility in society. Its philosophy is pro-life libertarian (rather than neo-conservative) on economic issues, adhering to biblical norms for proper social perspective but rarely looking to the state for solutions to social problems. POL provides resources, links, books and articles, an email list, photos and links to famous economists, great quotations for liberty.</p></td></tr>
<tr><td width="409" bgcolor="#CCCCCC" height="90" border="2" align="right"></td></tr></TABLE>
<table cellpadding="0" cellspacing="0" width="771" border="0" bgcolor="#999999">
<tr><td><img src="white.gif" height="3" width="771" alt="<? echo "$alt"?>"></td></tr>
<tr><td><p class="white"><b>The following books, written by Dr. John Cobin, are currently available:  <br>(Click on a book to read its description.)</b></p></td></tr><tr><td><img src="white.gif" height="3" width="771" alt="<? echo "$alt"?>"></td></tr></table>
<table cellpadding="0" cellspacing="0" width="771" border="0" bgcolor="#ffffff"><tr><td><IMG height="220" width="5" alt="<? echo "$alt"?>" src="white.gif" border="0"></td><td><a href="books1.php"><IMG height="220" alt="Building Regulation, Market Alternatives, and Allodial Policy" src="images/books1a.jpg" border="0"></a></td><td><a href="books2.php"><IMG height="220" alt="Pro-Life Policy: A Perspective for Liberty and Human Rights" src="images/books2a.jpg" border="0"></a></td><td><a href="books3.php"><IMG height="220" alt="Bible and Government: Public Policy from a Christian Perspective" src="images/Cover B & G without spine.jpg" border="0"></a></td><td><a href="books4.php"><IMG height="220" alt="Life In Chile: Personal Observations of an American Expatriate Academic" src="images/books4a.jpg" border="0"></a></td><td><a href="books5.php"><IMG height="220" alt="Christian Theology of Public Policy: Highlighting the American Experience" src="images/CTPP Cover Front only.jpg" border="0"></a></td></tr></table>
<table cellpadding="0" cellspacing="0" width="771" border="0"><? include ("base.php")?>