<?define ('wwwf_IN',true);
$title = "Will They Now Crucify the Man Who Rescued Chile?";
$desc = "Books/papers on free market economics and policy, pro-life policy, Cobin CV, links, photos, other resources, allodial title, fire safety regulation, building regulation, free market policy, drug legalization, abortion debate";
$key = "allodial title, allodialism, allodial policy, free market textbook, homeschool books, economics books for homeschoolers, public policy and Christians, creation and evolution, Christian homeschool books, public policy books, pro-life books, abortion issue, Christians and government, building regulation, allodial title, tax protesting, revolution, fire safety regulation, accreditation of higher education, public choice economics, Virginia school, Austrian economics, law and economics, subjectivist economics, knowledge problem, market failure, government failure, urban regulation, fire safety regulation, romantic vision of government, public, choice, Austrian, economics, law, rent seeking, right, allodial, regulation, policy, vote, government, Bible, pro-life, Christian, building, zoning, liberty, planning, market, Chile, abortion debate, public school, Romans 13, feudal, privatization, allodial property";
$alt = "Policy of Liberty is your source for books/papers on free market economics and pro-life policy as well as quotes and links to economic related issues";
$titleimg = "papers.jpg";include ("top.php")?>
<TABLE cellpadding="0" cellspacing="0" border="0" width="771" height="240">
<tr><td rowspan="2"><IMG height="240" alt="Will They Now Crucify the Man Who Rescued Chile?" src="images/paper.jpg" width="359" border="0"></td>
<td valign="top"><p class="pl">Policy of liberty is dedicated to the advancement of liberty and responsibility in society. Its philosophy is neither strictly libertarian nor strictly conservative, though strongly supporting the former in terms of economics and the latter on most social issues, abortion in particular. POL provides resources, links, books and articles, an email list, photos and links to famous economists, great quotations for liberty.</p></td></tr>
<tr><td width="409" bgcolor="#CCCCCC" height="90" border="2" align="right"></td></tr></TABLE>
<table cellpadding="0" cellspacing="0" width="771" border="0" bgcolor="#999999">
<tr><td><img src="white.gif" height="3" width="771" alt="<? echo "$alt"?>"></td></tr>
<tr><td><p class="white"><b>Will They Now Crucify the Man Who Rescued Chile?:</b></p></td></TD></tr></table>
<br><table width="771"><tr><td>
<p class="head" align="center"><B>Will They Now Crucify the Man Who Rescued Chile?</B></p>
<BR><P class="subhead" align="center">by John Cobin and Karen Araujo<br><p class="pl" align="center"><b>This article appeared in the <A HREF="http://www.libertysoft.com/liberty/issues/70issue.html" class="linc">February 1999 issue</A> of <I>Liberty</I></b></P>
<br><P class="pl">The world rarely quiets itself from wars and other conflicts, and few wars can be called just from a classically liberal perspective. Like America&#146;s War for Independence and the War Between the States, Chile&#146;s struggle against the communists was a just conflict. The revolution in Chile was an act of self defense against legal looters and armed bandits. As is inevitable in any war, errors were made and innocent lives lost. But despite its mistakes, the revolution left a positive legacy: Chile has a free and prosperous economy and stable republican institutions. This is the context in which the British arrest of General Augusto Pinochet, the leader of Chile&#146;s revolution, must be judged.</P>
<br><P class="pl">When Pinochet took over, Chile was experiencing a rapid decay in the quality of life. Salvador Allende had been elected president victory in a three-way election, in which he won a minority of the vote and immediately set about making himself into the dictator of a socialist country. There were reports of Allende killing dozens or even hundreds of people in the countryside. He was stealing and nationalizing private property. There was 1,000 percent inflation during his 1,000 days of rule. There was much hunger (for those who were not &#147;in&#148; with the socialists) and it was not uncommon to see people without shoes.</P>
<br><P class="pl">Hector Hevia, a Chilean professor who lived through those chaotic times recalls, &#147;You had to wait in line for hours to get a piece of meat you could not eat.&#148; By July 1973, Allende had centralized control of nearly everything, including replacing the top two men in every firm with a bureaucrat. In short, Allende was destroying people&#146;s lives, and Chileans had a right to defend themselves against him.</P>
<br><P class="pl">At the time, Chile was a battleground in the Cold War between the United States and the Soviet Union. President Allende had proved he was no democrat by calling for total power to the workers and by undertaking actions, akin to the socialist revolutions by the Cubans and the Soviets -- both of whose embassies in Santiago were overflowing with personnel. Chile was in chaos and armed groups of left and right were taking over the streets. Civil war was imminent.</P>
<br><P class="pl">There were massive demonstrations calling for Allende&#146;s resignation. On August 22, 1973, the Chilean chamber of deputies passed a resolution of censure against Allende. Congressional deputies condemned him and his government for violating the constitution and the law in order to &#147;institute a totalitarian system absolutely opposed to the representative system of government that the Constitution establishes,&#148; and called upon the military to intervene.</P>
<br><P class="pl">On September 11, the Chilean military ousted the Allende government. In less than 24 hours, the armed forces had consolidated control of the country. But the Marxists did not retreat quietly into the night. They reorganized and regrouped and continued to fight against the government. During the immediate aftermath of Allende&#146;s ouster, some innocent people were undoubtedly killed. In the tense early period of the military regime it was not uncommon for civilians falsely to accuse individuals of being armed leftists in order to settle private scores. But most of the people killed by the military were part of the of the armed left.</P>
<br><P class="pl">According to the report of the respected Rettig Commission of the democratic Aylwin government, there were 1,173 deaths, including military personnel, both during the revolution and in its aftermath, from September to December 1973. The Rettig Commission reported a total of 2,033 deaths perpetrated by the military during the 17-year military regime, and 265 deaths of military personnel, civilians killed by terrorists, and deaths due to general political violence. The deaths are undercounted on both sides, and the number of people who disappeared are included in the total.</P>
<br><P class="pl">The majority -- 63 percent -- of those killed were members of Marxist political parties, such as in the Movement of the Revolutionary Left, an entirely terrorist group, the Manuel Rodriguez Front, entirely terrorist, the Socialist and Communist parties, both of which had armed contingents, and of smaller, violent Marxist parties. Sola Sierra, president of the Group of the Relatives of the Arrested-Disappeared in Chile, herself a communist, stated that the percentage of people killed who were affiliated with Marxist parties was actually much higher, since relatives often feared to publicly reveal the political affiliation of the dead.</P>
<br><P class="pl">All wars have social costs, not the least of which are the occasional loss of innocent life, and Chile&#146;s anti-Marxist revolution was no exception. Chile&#146;s war with armed leftist terrorists from 1973 to 1990 led to some regrettable and tragic deaths of innocent people. Generals made mistakes in the heat of battle and the nature of guerrilla warfare makes the enemy particularly hard to identify. There were undoubtedly accidental killings.</P>
<br><P class="pl">What would Chile be like today without Pinochet? Take a look at Cuba, where people are starving during the 39th year of Marxist dictatorship. Most Chileans feel badly that innocent people died during Pinochet&#146;s war on Marxist terrorism in Chile, and they wish some things were done differently. But those who love liberty should be grateful that Pinochet came to resolve the chaos and terror fomented by the Marxists in the 1970s and 1980s, and usher in an era of peace, stable republican governance, and prosperity.</P>
<br><P class="pl">Now, the British have arrested Pinochet at the request of a Spanish court, seeking to prosecute him for various offenses committed during the revolution. He stands accused of genocide and murder, and everyone knows that. Western news media seldom reported the terrorist activities of the communists that Pinochet fought, and Pinochet gets little sympathy in Europe or North America.</P>
<br><P class="pl">Things are very different here in Chile. Most people we have talked to are uneasy, sad, and even outraged about the arrest. Recent polls put popular support in Chile for Pinochet&#146;s release at over 75 percent. Alvaro Vial, academic Vice President at Finis Terrae University, who frequently writes on Chilean political issues for the national press, said that he believes that perhaps 40 percent of Chileans would firmly stand behind Pinochet. Then there are probably another 30 to 40 percent who support his return to Chile out of reasons of nationalism, if nothing else. The vast majority of Chileans want Pinochet to be freed.</P>
<br><P class="pl">There are frequent pro-Pinochet demonstrations in front of the British and Spanish embassies which sometimes turn violent, as demonstations here often do. The boulevard in front of the Spanish embassy is at times sealed off and that embassy, along with the British Ambassador&#146;s residence, are continually barricaded.</P>
<br><P class="pl">As Americans living in Santiago, we see that many Chileans feel helpless in this situation. They resent that the world does not seem to care about their views on an issue which is of utmost importance to them. The man who saved Chile from so much anguish at the hands of Marxists has now been caught in a snare set by their leftist compatriots in Europe. Rather than go after the true criminals who retain power by force (Fidel Castro comes immediately to mind) the world now watches as the mighty left seeks to destroy the man who saved Chile from socialist hell.</P>
<br><P class="pl">We think Pinochet&#146;s supporters in Chile have a good point. To charge Pinochet with murder would be as unjust as charging Patrick Henry or Thomas Jefferson with murdering Redcoats or with accidentally shooting a neighbor while trying to kill a Redcoat. All such revolutionaries act in self defense against an oppressive state, and thus their cause is just, despite tragedies and accidental loss of innocent lives that might occur.</P>
<br><P class="pl">The media in the United States and in Europe have distorted the facts regarding Pinochet. He stands accused of murder and crimes against humanity, and that is the beginning and the end of the story as far as most journalists are concerned. But CNN and of the international news media rarely reveal details about the terrorist activities of the communists that Pinochet was fighting. Because of their mostly leftist bias, most media do not sympathize with Pinochet, or with his revolution against armed socialists who pushed the country to civil war.</P>
<br><P class="pl">Thus, the media portray Pinochet as a senseless and brutal dictator and ignore the circumstances in which Pinochet assumed power: to prevent a bloody, protracted civil war.  Pinochet, and those under his command, almost certainly were responsible for the death of innocent people. In the chaos and confusion of war, such tragedies are inevitable. Those outside the fray would do well to hesitate to pass judgment on the fallible human beings swept up in the vortex of war. Pinochet was not pure; no one could be, ever has been, or ever will be under such circumstances.</P>
<br><P class="pl">The American Revolution itself had its share of similar tragedies. Does that melancholy fact erase the good that was accomplished -- the establishment of a free society and the defeat of tyranny? Make no mistake about it: whatever mistakes he made along the way, Pinochet&#146;s actions resulted in the creation of stable republican institutions and the transformation of a ruined economy into a prosperous one, to the benefit of all Chileans.</P>
<br><P class="pl">Pinochet carried out an economic and political revolution that successively devolved power away from the state. Afterward he voluntarily stepped down from power. In doing so, his successors agreed to give him immunity from prosecution for misdeeds committed during the revolution. To us, this seems like a reasonable arrangement; the revolution was over, peace, prosperity, and a stable republic stood in the place of chaos, poverty and dictatorship.</P>
<br><P class="pl">Classical liberals cannot exonerate Pinochet for any true crimes he committed, but we should be willing to view his deeds in the context of the terrorist war in which they were made. And we should we give him credit for relinquishing power voluntarily. Pinochet was no tyrant. Do tyrants usher in more freedom? Do they relinquish their power voluntarily? Pinochet did both.</P>
<br><P class="pl">Simultaneously, we have to recall that the &#147;revolution&#148; that the Marxist terrorists in the MIR, FMR, and Communist and Socialist parties were fighting for against the Pinochet government was not to create a freer society. Rather, if successful, the Marxists would have re-imposed a socialist dictatorship on Chile.</P>
<br><P class="pl">While one cannot completely exonerate Pinochet, he is far less culpable than any number of living Chinese, Cuban, and North Korean rulers in terms of human rights violations. Those leftist leaders apparently can wave their iron scepters and commit atrocities without fear of international reprisals.</P>
<br><P class="pl">What an absurd precedent Pinochet&#146;s arrest sets. Monsters like Zaire&#146;s Mobutu, Cambodia&#146;s Pol Pot, and most of the dictators of the communist countries of eastern Europe were not harangued by world tribunals and the press.  But Pinochet, who voluntarily stepped down from office and now continues to serve his country as a member of its Senate, is arrested when he visits Britain!</P>
<br><P class="pl">It is difficult to fathom why the British government arrested Pinochet, apart from public choice possibilities. Apparently playing off the ignorance about what happened in Chile 25 years ago, British politicians figure that they can assail Pinochet, a controversial  but relatively unknown figure from a small, far-off country. They thus become easy patrons of virtue, garners of the public welfare, and winners of votes.</P>
<br><P class="pl">The British, Swiss, and Spanish apparently think it is fine for their governments to hold Pinochet accountable for the things he did during the terrorist war regardless of what was happening in Chile at the time that caused him to act as he did. Why don&#146;t they give him a peace prize for saving so many people? It seems that one could make that case more strongly than a murder case, at least if one wants to try to calculate net social benefits (which seems to be popular among interventionist courts driven by social justice concerns). More importantly, should classical liberals support the emergence of a one-world court, which would enable the interventionist state to rule conduct on a global scale?</P>
<br><P class="pl">Those want to point out the faults of Pinochet must be careful lest their arguments condemn Thomas Jefferson, Simon Bolivar, Patrick Henry, George Washington, and Robert E. Lee as well. We admire Pinochet, as we admire Jefferson, Bolivar, and other champions of freedom for the overall good that each did, and the justice of the cause of fighting tyranny to which they devoted their lives. Thus, we are willing to overlook many of their errors as tragedies of history and indirect consequences of living in a world dominated by the evil and interventionist state.</P>
<br><P class="pl">Anyone who cares about the truth ought to weigh Pinochet&#146;s heroic accomplishments against the spurious claims of a biased media and self-righteous European hypocrites. In the end, whatever his faults, Pinochet has done more for the cause of freedom than all of them put together.</P></P></td></tr></table><br>
<table cellpadding="0" cellspacing="0" width="771" border="0"><? include ("base.php")?>
