<?define ('wwwf_IN',true);
$title = "Academic Journals and Scholarly Publications";
$desc = "Books/papers on free market economics and policy, pro-life policy, Cobin CV, links, photos, other resources, allodial title, fire safety regulation, building regulation, free market policy, drug legalization, abortion debate";
$key = "allodial title, allodialism, allodial policy, free market textbook, homeschool books, economics books for homeschoolers, public policy and Christians, creation and evolution, Christian homeschool books, public policy books, pro-life books, abortion issue, Christians and government, building regulation, allodial title, tax protesting, revolution, fire safety regulation, accreditation of higher education, public choice economics, Virginia school, Austrian economics, law and economics, subjectivist economics, knowledge problem, market failure, government failure, urban regulation, fire safety regulation, romantic vision of government, public, choice, Austrian, economics, law, rent seeking, right, allodial, regulation, policy, vote, government, Bible, pro-life, Christian, building, zoning, liberty, planning, market, Chile, abortion debate, public school, Romans 13, feudal, privatization, allodial property";
$alt = "Policy of Liberty is your source for books/papers on free market economics and pro-life policy as well as quotes and links to economic related issues";
$titleimg = "papers.jpg";
include ("top.php")?>
<!-- start page content -->
<TABLE cellpadding="0" cellspacing="0" border="0" width="771" height="240">
<tr><td rowspan="2"><IMG height="240" alt="Academic Journals and Scholarly Publications" src="images/paper.jpg" width="359" border="0"></td>
<td valign="top"><p class="pl"><b>Policy of Liberty</b> is dedicated to the advancement of liberty and responsibility in society. Its philosophy is libertarian, strongly supporting free markets while maintaining a conservative stance on some key social issues like <a href="http://www.l4l.org">abortion</a>. POL provides resources, links, books and articles, an email list, photos and links to famous economists, great quotations for liberty.</p></td></tr>
<tr><td width="409" bgcolor="#CCCCCC" height="90" border="2" align="right"></td></tr></TABLE>
<br>
<br>

<table cellpadding="0" cellspacing="0" width="771" border="0" bgcolor="#99944a">
<tr><td><p class="white"><i>Note: <a href="http://www.adobe.com/acrobat">Adobe Acrobat</a> is required to view many of the following papers and articles.</i></p></td></TD></tr></table>
<table cellpadding="0" cellspacing="0" width="771" border="0" bgcolor="#999999">
<tr><td><img src="white.gif" height="3" width="771" alt="Policy of Liberty is your source for books/papers on free market economics and pro-life policy as well as quotes and links to economic related issues"></td></tr>
<tr><td><p class="white"><b><i>Academic Journals and Scholarly Publications</i></b></p></td></tr></table>

<table valign="top" cellpadding="0" cellspacing="0" WIDTH="771" border="1">
	<tr bgcolor="#C0C0C0"><td class="pl"><b>Date</b></td><td class="pl"><b>Title</b></td><td class="pl"><b>Link</b></td></tr>
	<tr><td class="pl">September 1999</td><td class="pl"><b>“Market Provision of Highways: Lessons from Costanera Norte”</b>, <i>Planning and Markets</i>, vol. 2, no. 1</td><td class="pl"> See the <a href="http://www-pam.usc.edu/" class="linc">online journal page</a> or view the <a href="http://www-pam.usc.edu/volume2/v2i1a3s1.html#Cobin_contents" class="linc">article online</a></td></tr>
	<tr><td class="pl">September 2000</td><td class="pl"><b>“Fire Safety and Building Regulation in Eastern Santiago, Chile”</b>, <i>Planning and Markets</i>, vol. 3, no. 1</td><td class="pl">   See a report on the article by <i>El Mercurio</i> <a href="einterview.php" class="linc">on this page</a>. See the <a href="http://www-pam.usc.edu/" class="linc">online journal page</a> or view the <a href="http://www-pam.usc.edu/volume3/v3i1a2s1.html">article online</a>.</td></tr>
	<tr><td class="pl">1999</td><td class="pl"><b>“Allodialism as Economic Policy”</b>, 1999, Commentaries on Law &amp; Economics, vol. 3</td><td class="pl">Click <a href="http://papers.ssrn.com/sol3/papers.cfm?abstract_id=186934" class="linc">here</a> to read the abstract</td></tr>
	<tr><td class="pl">September 2003</td><td class="pl"><b>“Abortion Policy and the Market”</b>, <a href="http://www.jis3.org/"><i>Journal of Interdisciplinary Studies</i></a>, vol. 15.  Re improving the Futures-of-Value thesis and the pro-life position with market failure theory and Julian Simon's thesis.</td><td class="pl">Click <a href="http://www.policyofliberty.net/e-books/Abortion Policy and the Market.pdf">here</a> to read the paper.</td></tr>
	<tr><td class="pl">September 2004</td><td class="pl"><b>“Book Review of <i>The Market Driven Church</i> by Udo Middelmann”</b>, <a href="http://www.jis3.org/"><i>Journal of Interdisciplinary Studies</i></a>, vol. 16.</td></tr>
	<tr><td class="pl">1998</td><td class="pl"><b>“Siegan brought Up-to-Date: A Critical View of the Expansion of Zoning in Santiago”</b>, <a href="http://www.mises.org/scholar_interests.asp" class="linc">Working papers</a> series of the Mises Institute.</a></td><td class="pl"> <a href="http://www.mises.org/journals/scholar/cobin.PDF">PDF link</a></td></tr>
	<tr><td class="pl">1998</td><td class="pl"><b>“A Note on Altering Regulation of Higher Education in Chile”</b>, The Spanish translation was published as “Modificaciones a la Regulación de la Educación Superior en Chile”, Serie Informe Social of <a href="http://www.lyd.cl/" class="linc">Instituto Libertad y Desarrollo</a>, Santiago, Chile, no. 56, December 1999, pp. 1-35.</td></tr>
	<tr><td class="pl">2000</td><td class="pl"><b>“Price Disparity and Imperfect Information in Major Supermarkets in Santiago, Chile”</b> (unpublished manuscript)</td></tr>
	<tr><td class="pl">2000</td><td class="pl"><b>“Murray N. Rothbard and Israel M. Kirzner: Recent "Deans" of the Modern Austrian School of Economics”</b>  A compendium compiled and edited by Dr. Cobin under the auspices of Centro de Estudios Públicos, Santiago, Chile in order to provide Spanish speakers with access to some key portions of the work of Murray Rothbard and Israel Kirzner.</td><td class="pl"> The English version is on the <a href="http://www.mises.org/scholar_interests.asp" class="linc">Working papers</a> page of the Mises Institute.</td></tr>
	<tr><td class="pl">2001</td><td class="pl"><b>“James M. Buchanan and Gordon Tullock: A Compendium of a Half Century of Thought”</b>  A compendium compiled and edited by Dr. Cobin under the auspices of Centro de Estudios Públicos, Santiago, Chile in order to provide Spanish speakers with access to some key portions of the "public choice" work of James M. Buchanan and Gordon Tullock.</td><td class="pl"> Was to be published in Spanish in <i>Estudios Públicos</i> in 2001. <a href="http://www.gmu.edu/jbc/fest/LATE_ENTRIES.htm" class="linc">English version</a> is on the <a href="http://www.gmu.edu/jbc/fest/index.html" class="linc">Buchanan Project page</a>.</td></tr>
</table>
<BR><BR>
<table cellpadding="0" cellspacing="0" width="771" border="0" bgcolor="#999999">
<tr><td><img src="white.gif" height="3" width="771" alt="Policy of Liberty is your source for books/papers on free market economics and pro-life policy as well as quotes and links to economic related issues"></td></tr>
<tr><td><p class="white"><b><i>Newspapers and Magazines</i></b></p></td></TD></tr></table><table cellpadding="0" cellspacing="0" width="771" border="0" bgcolor="#99bc5a">
<tr><td><img src="white.gif" height="3" width="771" alt="Policy of Liberty is your source for books/papers on free market economics and pro-life policy as well as quotes and links to economic related issues"></td></tr>
<tr><td><p class="white"><b><i>The Times Examiner</i></b> weekly column</p></td></tr></table>

<table cellpadding="0" cellspacing="0" WIDTH="771" border="1">
	<tr bgcolor="#C0C0C0"><td class="pl"><b>Date</b></td><td class="pl"><b>Title</b></td><td class="pl"><b>Link</b></td><td class="pl"><b>Audio File</b></td><td class="pl"><b>Spanish Trans.</b></td></tr>
	<tr><td class="pl">June 9, 2004</td><td class="pl"><b>“Dealing with Growth (and Central Planners)”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Dealing with Growth and Central Planners.pdf">Read it online</a></td></tr>
	<tr><td class="pl">June 23, 2004</td><td class="pl"><b>“The Real Problem with the FTAA and Immigration”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/The Real Problem with the FTAA and Immigration.pdf">Read it online</a></td></tr>
	<tr><td class="pl">June 30, 2004</td><td class="pl"><b>“Finally A True Right Wing Presidential Candidate (Michael Badnarik)”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Finally A True Right Wing Presidential Candidate.pdf">Read it online</a></td></tr>
	<tr><td class="pl">July 7, 2004</td><td class="pl"><b>“Environmental Quackery”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Enviromnental Quackery.pdf">Read it online</a></td></tr>
	<tr><td class="pl">July 14, 2004</td><td class="pl"><b>“Recycling Idiocy”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Recycling Idiocy.pdf">Read it online</a></td></tr>
	<tr><td class="pl">August 4, 2004</td><td class="pl"><b>“Marriage Amendment Muddle”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Marriage Amendment Muddle.pdf">Read it online</a></td></tr>
	<tr><td class="pl">August 11, 2004</td><td class="pl"><b>“Water Shortage?”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Water Shortage.pdf">Read it online</a></td></tr>
	<tr><td class="pl">August 18, 2004</td><td class="pl"><b>“Blaming Everything (Even Floods) on Growth”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Blaming Everything (Even Floods) on Growth.pdf">Read it online</a></td></tr>
	<tr><td class="pl">August 25, 2004</td><td class="pl"><b>“Chemical Warfare: the Misery of Environmentalism”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Chemical Warfare.pdf">Read it online</a></td></tr>
	<tr><td class="pl">September 1, 2004</td><td class="pl"><b>“Alternative Energy Is Not Viable”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Alternative Energy Is Not Viable.pdf">Read it online</a></td></tr>
	<tr><td class="pl">September 8, 2004</td><td class="pl"><b>“The Global Warming Myth”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Global Warming Myth.pdf">Read it online</a></td></tr>
	<tr><td class="pl">September 15, 2004</td><td class="pl"><b>“The Overpopulation Myth”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Overpopulation Myth.pdf">Read it online</a></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Overpopulation Myth (Spanish).pdf">español</a></td></tr>
	<tr><td class="pl">September 22, 2004</td><td class="pl"><b>“Are We Running Out of Natural Resources?”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Running Out of Resources.pdf">Read it online</a></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Running Out of Resources (Spanish).pdf">español</a></td></tr>
	<tr><td class="pl">September 29, 2004</td><td class="pl"><b>“Pollution Is Not Getting Worse”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Pollution Is Not Getting Worse.pdf">Read it online</a></td></tr>
	<tr><td class="pl">October 2004</td><td class="pl"><b>“Rogue Judge Falsely Imprisons Man for Eight Months”</b><br> [published in <i>The Truth Newspaper</i>, vol. 1, issue 12, and elsewhere online]</td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Rogue Judge Falsely Imprisons Man for 8 Months.pdf">Read it online</a></td></tr>
	<tr><td class="pl">October 13, 2004</td><td class="pl"><b>“Government Perpetuates Smog”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Government Perpetuates Smog.pdf">Read it online</a></td></tr>
	<tr><td class="pl">October 20, 2004</td><td class="pl"><b>“The Power of Homeschooling Mothers”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Power of Homeschooling Mothers.pdf">Read it online</a></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Power of Homeschooling Mothers (Spanish).pdf">español</a></td></tr>
	<tr><td class="pl">October 27, 2004</td><td class="pl"><b>“Homeschooling Is a Doable Alternative”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Homeschooling Is a Doable Alternative.pdf">Read it online</a></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Homeschooling Is a Doable Alternative (Spanish).pdf">español</a></td></tr>
	<tr><td class="pl">November 3, 2004</td><td class="pl"><b>“Privatizing Social Security Via the Macabre”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Privatizing Social Security Via the Macabre.pdf">Read it online</a></td></tr>
	<tr><td class="pl">November 10, 2004</td><td class="pl"><b>“Pragmatism Is Not a Third Party Principle”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Pragmatism Is Not a Third Party Principle.pdf">Read it online</a></td></tr>
	<tr><td class="pl">November 17, 2004</td><td class="pl"><b>“The Clay-Hamilton-Lincoln Cult Resurgence Within Conservatism”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/The Clay-Hamilton-Lincoln Cult Resurgence Within Conservatism.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 011805 Leftist Conservatives mix.mp3">audio</a></td></tr>
	<tr><td class="pl">November 24, 2004</td><td class="pl"><b>“Ciudad del Este: A Free-Market Spectacle”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Ciudad del Este a Free-Market Spectacle.pdf">Read it online</a></td></tr>
	<tr><td class="pl">December 1, 2004</td><td class="pl"><b>“Free-Market Solutions for Immigration Problems”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Free-Market Solutions for Immigration Problems.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 012005 Free Market Immigration mix.mp3">audio</a></td></tr>
	<tr><td class="pl">December 8, 2004</td><td class="pl"><b>“Patriot Act Havoc Yields TSA Hassles”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Patriot Act Havoc Yields TSA Hassles.pdf">Read it online</a></td></tr>
	<tr><td class="pl">December 15, 2004</td><td class="pl"><b>“Christian Radio Station Loses Its Savor”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Radio Station Goes Left.pdf">Read it online</a></td></tr>
	<tr><td class="pl">December 22, 2004</td><td class="pl"><b>“CP Ideas vs. Pro-Life LP Ideas”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/CP Ideas vs Pro-Life LP Ideas.pdf">Read it online</a></td></tr>
	<tr><td class="pl">December 29, 2004</td><td class="pl"><b>“Our Enemy, the Government School”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Our Enemy the Government School.pdf">Read it online</a></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Our Enemy the Government School (Spanish).pdf">español</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LMS 010505 Escuela Publica Nuestro Enemigo mix.mp3">escuchar</a></td></tr>
	<tr><td class="pl">January 5, 2005</td><td class="pl"><b>“Drugs and Perverse Incentives”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Drugs and Perverse Incentives.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 010505 Drugs mix.mp3">audio</a></td></tr>
	<tr><td class="pl">January 10, 2005</td><td class="pl"><b>“Financial Planning with the "Right" Perspective”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Financial Planning with the Right Perspective.pdf">Read it online</a></td></tr>
	<tr><td class="pl">January 12, 2005</td><td class="pl"><b>“Government Aid for Tsunami Victims Is Wrong”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Government Aid for Tsunami Victims Is Wrong.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 010705 Tsunami Aid mix.mp3">audio</a></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Government Aid for Tsunami Victims Is Wrong (Spanish).pdf">español</a></td></tr>
	<tr><td class="pl">January 19, 2005</td><td class="pl"><b>“Government vs. the State”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Government vs State.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 011705 Govt v State mix.mp3">audio</a></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Government vs State (Spanish).pdf">español</a></td></tr>
	<tr><td class="pl">January 26, 2005</td><td class="pl"><b>“Why License Marriages?”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Why License Marriages.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 011905 Marriage mix.mp3">audio</a></td></tr>
	<tr><td class="pl">February 2, 2005</td><td class="pl"><b>“Covenant Marriage Concerns”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Covenant Marriage Concerns.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 020405 Marriage Covenant Concerns mix.mp3">audio</a></td></tr>
	<tr><td class="pl">February 9, 2005</td><td class="pl"><b>“The Lottery Is the Best Tax”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/The Lottery Is the Best Tax.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 021105 Lottery Best Tax.mp3">audio</a></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/The Lottery Is the Best Tax (Spanish).pdf">español</a></td></tr>
	<tr><td class="pl">February 16, 2005</td><td class="pl"><b>“Are State Lotteries Immoral? (Part 1)”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Are State Lotteries Immoral Part 1.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 030105 Lottery Immoral.mp3">audio</a></td></tr>
	<tr><td class="pl">February 23, 2005</td><td class="pl"><b>“Are State Lotteries Immoral? (Part 2)”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Are State Lotteries Immoral Part 2.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 030105 Lottery Immoral.mp3">audio</a></td></tr>
	<tr><td class="pl">March 2, 2005</td><td class="pl"><b>“Give Parents Their Proper Charge”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Giving Parents Their Proper Charge.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 030205 PPIC.mp3">audio</a></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Giving Parents Their Proper Charge (Spanish).pdf">español</a></td></tr>
	<tr><td class="pl">March 9, 2005</td><td class="pl"><b>“A Liberty Alternative to the PPIC Act”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/A Liberty Alternative to the PPIC Act.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 030205 PPIC.mp3">audio</a></td></tr>
	<tr><td class="pl">March 16, 2005</td><td class="pl"><b>“What Is a 'Neoconservative'?”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/What Is a Neoconservative.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 032305 Neocons.mp3">audio</a></td></tr>
	<tr><td class="pl">March 23, 2005 thru May 4, 2005</td><td class="pl"><b>“Christian Views on Rebellion” (in 7 Parts)</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Christian Views on Rebellion.pdf">Read it online</a></td></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 032205 Rebellion.mp3">audio</a></td></tr>
	<tr><td class="pl">May 11, 2005 thru May 18, 2005</td><td class="pl"><b>“Christians and Self-Defense against Criminals—Including the State” (in 2 Parts)</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Christians and Self-Defense against Criminals (Including the State).pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 050905 Self-Defense.mp3">audio</td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Christians and Self-Defense against Criminals (Including the State) (Spanish).pdf">español</a></td></tr>
	<tr><td class="pl">May 25, 2005 thru June 1, 2005</td><td class="pl"><b>“The Divine Ordination of State Criminals and Legalized Crime” (in 2 Parts)</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/The Divine Ordination of State Criminals and Legalized Crime.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 052305 Divine Ordination.mp3">audio</a></td></tr>
	<tr><td class="pl">June 8, 2005 thru June 15, 2005</td><td class="pl"><b>“Public Policy Theology in Historical Context” (in 2 Parts)</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Public Policy Theology in Historical Context.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 060605 Biblical Theology in Historical Context.mp3">audio</a></td></tr>
	<tr><td class="pl">June 22, 2005 thru July 6, 2005</td><td class="pl"><b>“The Second Amendment and Public Policy Theology” (in 3 Parts)</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/The Second Amendment and Public Policy Theology.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 062005 The Second Amendment and Public Policy Theology.mp3">audio</a></td></tr>
	<tr><td class="pl">July 13, 2005 thru July 27, 2005</td><td class="pl"><b>“Rights, Just War, and Public Policy Theology” (in 3 Parts)</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Rights, Just War, and Public Policy Theology.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 071105 Rights, Just War, and Public Policy Theology.mp3">audio</a></td></tr>
	<tr><td class="pl">August 3, 2005</td><td class="pl"><b>“Libertarian Social Policy”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Libertarian Social Policy.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 071805 Libertarian Social Policy.mp3">audio</a></td></tr>
	<tr><td class="pl">August 10, 2005 thru August 24, 2005</td><td class="pl"><b>“The Theology of Public Policies of Enslavement” (in 3 Parts)</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/The Theology of Public Policies of Enslavement.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 080305 The Theology of Public Policies of Enslavement.mp3">audio</a></td></tr>
	<tr><td class="pl">August 31, 2005 thru September 28, 2005</td><td class="pl"><b>“The Theology of Nations and Nationalism” (in 5 Parts)</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/The Theology of Nations and Nationalism.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 082905 The Theology of Nations and Nationalism.mp3">audio</a></td></tr>
	<tr><td class="pl">October 5, 2005 thru October 19, 2005</td><td class="pl"><b>“The Nature of the State” (in 3 Parts)</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/The Nature of the State.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 090905 The Nature of the State.mp3">audio</a></td></tr>
	<tr><td class="pl">October 26, 2005 thru November 2, 2005</td><td class="pl"><b>“Christian Civic Duty in America” (in 2 Parts)</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Christian Civic Duty in America.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 101005 Christian Civic Duty in America.mp3">audio</a></td></tr>
	<tr><td class="pl">November 9, 2005 thru November 16, 2005</td><td class="pl"><b>“The Christian Fight for Peace” (in 2 Parts)</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/The Christian Fight for Peace.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 101105 The Christian Fight for Peace.mp3">audio</a></td></tr>
	<tr><td class="pl">November 23, 2005 thru November 30, 2005</td><td class="pl"><b>“Self-Interested Political Actors” (in 2 Parts)</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Self-Interested Political Actors.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 102405 Self-Interested Political Actors.mp3">audio</a></td></tr>
	<tr><td class="pl">December 7, 2005 thru December 14, 2005</td><td class="pl"><b>“Tyranny of the FCC” (in 2 Parts)</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/FCC Tyranny.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 112205 FCC Tyranny.mp3">audio</a></td></tr>
	<tr><td class="pl">December 21, 2005 thru December 28, 2005</td><td class="pl"><b>“Christianity and Torture” (in 2 Parts)</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Christianity and Torture.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 112305 Christianity and Torture.mp3">audio</a></td></tr>
	<tr><td class="pl">January 4, 2006 thru January 11, 2006</td><td class="pl"><b>“Brave New Singapore” (in 2 Parts)</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Brave New Singapore.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 011306 Brave New Singapore.mp3">audio</a></td></tr>
	<tr><td class="pl">January 18, 2006 thru January 25, 2006</td><td class="pl"><b>“Hong Kong and Macau: Icons of Freedom” (in 2 Parts)</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Hong Kong and Macau Icons of Freedom.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 011606 Hong Kong and Macau Icons of Freedom.mp3">audio</a></td></tr>
	<tr><td class="pl">February 1, 2006 thru February 8, 2006</td><td class="pl"><b>“Thailand: Friendly, Fun, and Becoming Less Free” (in 2 Parts)</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Thailand Friendly Fun and Becoming Less Free.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 013006 Thailand Friendly Fun and Becoming Less Free.mp3">audio</a></td></tr>
	<tr><td class="pl">February 15, 2006 thru February 22, 2006</td><td class="pl"><b>“Is Rebellion against Rulers Rebellion against God?” (in 2 Parts)</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Is Rebellion against Rulers Rebellion against God.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 021806 Is Rebellion against Rulers Rebellion against God.mp3">audio</a></td></tr>
	<tr><td class="pl">March 1, 2006</td><td class="pl"><b>“Adversity Makes Strange Bedfellows”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Adversity Makes Strange Bedfellows.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 022506 Adversity Makes Strange Bedfellows.mp3">audio</a></td></tr>
	<tr><td class="pl">March 8, 2006 thru March 22, 2006</td><td class="pl"><b>“Extremists Are Too Hot for Modern Churches to Handle” (in 3 Parts)</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Extremists Are Too Hot for Modern Churches to Handle.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/LM 030606 Extremists Are Too Hot for Modern Churches to Handle.mp3">audio</a></td></tr>
	<tr><td class="pl">March 29, 2006</td><td class="pl"><b>“Of Republicrats and Demublicans”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Of Republicrats and Demublicans.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/Republicrats.mp3">audio</a></td></tr>
	<tr><td class="pl">April 12, 2006</td><td class="pl"><b>“Outsourcing Bob Inglis: The Tragic Saga of a Liberal Republican”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Outsourcing Bob Inglis The Tragic Saga of a Liberal Republican.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/Inglis.mp3">audio</a></td></tr>
	<tr><td class="pl">April 19, 2006</td><td class="pl"><b>“Big Brother Bob Inglis”</b></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Big Brother Bob Inglis.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/Big Brother Bob Inglis.mp3">audio</a></td></tr>
	<tr><td class="pl">August 1, 2006</td><td class="pl"><b>“Privatizing U.S. Border Offers a Good Solution”</b><br> [published in <a href="http://www.greenvilleonline.com/apps/pbcs.dll/article?AID=/20060801/OPINION/608010322/1008"><i>The Greenville News</i>, page 7A]</A></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Privatizing U.S. Border Offers a Good Solution.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/Privatizing U.S. Border Offers a Good Solution.mp3">audio</a></td></tr>
	<tr><td class="pl">August 30, 2006</td><td class="pl"><b>“Are You Sick of Paying $3 for Gas?”</b><br> [written for <i>The Greenville News</i>, editorial page ]</A></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Are You Sick of Paying $3 for Gas.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/Are You Sick of Paying $3 for Gas.mp3">audio</a></td></tr>
	<tr><td class="pl">September 5, 2006</td><td class="pl"><b>“Your Congressman and Abortion”</b><br> [written for <i>The Greenville News</i>, editorial page ]</A></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Your Congressman and Abortion.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/Your Congressman and Abortion.mp3">audio</a></td></tr>
	<tr><td class="pl">September 25, 2006</td><td class="pl"><b>“Proverbs Women”</b></A></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Proverbs Women.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/Proverbs Women.mp3">audio</a></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Mujeres de proverbios.pdf">español</a></tr>
	<tr><td class="pl">August 13, 2007</td><td class="pl"><b>“Mothers Who Kill Their Kids”</b></A></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Mothers Who Kill Their Kids.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/Mothers Who Kill Their Kids.mp3">audio</a></td></tr>
	<tr><td class="pl">August 22, 2007</td><td class="pl"><b>“What about the Onslaught of Hurricanes?”</b></A></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/What about the Onslaught of Hurricanes.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/What about the Onslaught of Hurricanes.mp3">audio</a></td></tr>
	<tr><td class="pl">August 24, 2007</td><td class="pl"><b>“Your Citizenship and the IRS”</b></A></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Your Citizenship and the IRS.pdf">Read it online</a></td><td class="pl"><a href="http://www.PolicyOfLiberty.net/Liberty Minute/Your Citizenship and the IRS.mp3">audio</a></td></tr>
</table>
<br>

<table cellpadding="0" cellspacing="0" width="771" border="0" bgcolor="#99bc5a">
<tr><td><img src="white.gif" height="3" width="771" alt="Policy of Liberty is your source for books/papers on free market economics and pro-life policy as well as quotes and links to economic related issues"></td></tr>
<tr><td><p class="white"><b>Columns in Other Newspapers</b></p></td></tr></table>

<table cellpadding="0" cellspacing="0" WIDTH="771" border="1">
	<tr bgcolor="#C0C0C0"><td class="pl"><b>Date</b></td><td class="pl"><b>Title</b></td><td class="pl"><b>Link</b></td></tr>
	<tr><td class="pl">June 2000</td><td class="pl"><b><b><a href="LetterLibertyHomeschool.php" class="linc">Letter to the Editor of Liberty magazine defending homeschooling</b></a></td><td class="pl"><a href="http://www.policyofliberty.net/e-books/Dealing with Growth and Central Planners.pdf">Read it online</a></td></tr>
	<tr><td class="pl">February 2000</td><td class="pl"><b>“Los Nuevos Presidentes Socialistas”</b></td><td class="pl">published in various papers in Latin America: <a href="http://www.gestion.com.pe/" class="linc">GESTIÓN</a>, the newspaper of economics and business, Lima, Perú, February 3, 2000, "Opinion" section; <a href="http://www.laprensa.com.ni/" class="linc">La Prensa</a>, Managua, Nicaraugua, February 4, 2000, "Opinion" section; and in <a href="http://www1.epasa.com/error/200.html" class="linc">El Panamá América,</a> Panamá, February 5, 2000, <a href="http://www1.epasa.com/error/200.html" class="linc">"Opinion" section</a>. Click <a href="PresidentesSocialistas.htm" class="linc">here</a> to read it (Spanish).</td></tr>
	<tr><td class="pl">September 1, 1997</td><td class="pl"><b><a href="gif/Mercurio1997EleccionPublica.jpg" class="linc">“Teoria de Elección Pública”</b></td><td class="pl"><i>El Mercurio</i> (Santiago, Chile), page A2</td></tr>
	<tr><td class="pl">February 1999</td><td class="pl"><b><a href="http://www.libertysoft.com/liberty/issues/70issue.html" class="linc">“Will They Now Crucify the Man Who Rescued Chile?”</b></a> [co-authored with Karen Araujo]</td><td class="pl"><i>Liberty</i>.  It can be seen at <A HREF="http://www.libertysoft.com/liberty/issues/70issue.html" class="linc"><U><I>Liberty</I>'s home page</U></A> and read <A HREF="CobinAraujo.php" class="linc">by clicking here</A>]. Also see the <a href="http://www.ideazione.com/Interazione/3-2000_15-21_02_2000/mingardi.htm" class="linc">interview (in Italian)</a> with Dr. Cobin by <i>Interazione</i> about the Pinochet case: "dagli Usa per riabilitare il 'criminale' Pinochet" by Alberto Mingardi (February 2000).</td></tr>
	<tr><td class="pl">July 1989</td><td class="pl"><b>“Spurgeon's View of Preaching”</b></td><td class="pl"><i>The Banner of Truth</i>, pages 18-23.</td></tr>
</table>
<br>

<table cellpadding="0" cellspacing="0" width="771" border="0" bgcolor="#90ba53">
<tr><td><img src="white.gif" height="3" width="771" alt="Policy of Liberty is your source for books/papers on free market economics and pro-life policy as well as quotes and links to economic related issues"></td></tr>
<tr><td><p class="white"><b>Court Briefs re Income Taxes</b></p></td></tr></table>

<table cellpadding="0" cellspacing="0" WIDTH="771" border="1">
	<tr><td class="pl"><b><A HREF="http://www.PolicyOfLiberty.net/e-books/Court Brief Notice No Income Tax Liability Underlying Legal Basis.pdf" class="linc">Court Brief Notice No Income Tax Liability Underlying Legal Basis</b></a></td></tr>
</table>
<br>

<p class="pl"><b>(<i>Note: the following PDF e-papers are available for low-cost purchase at the <a href="http://policyofliberty.net/checkout/products.php">Alertness books Bookstore</a></i>)</b></p>
<table cellpadding="0" cellspacing="0" width="771" border="0" bgcolor="#999999">
<tr><td><img src="white.gif" height="3" width="771" alt="Policy of Liberty is your source for books/papers on free market economics and pro-life policy as well as quotes and links to economic related issues"></td></tr>
<tr><td><p class="white"><b><i>Policy of Liberty Position Papers</i></b></p></td></TD></tr></table>
<table cellpadding="0" cellspacing="0" WIDTH="771" border="1">
	<tr bgcolor="#C0C0C0"><td class="pl"><b>Year</b></td><td class="pl"><b>Title</b></td></tr>
	<tr><td class="pl">2000</td><td class="pl"><b><a href="http://www.westga.edu/~bquest/2000/nzealand.html" class="linc">“Is New Zealand Really the 3rd Freest Place in the World?”</b></a> <a href="http://www.westga.edu/~bquest/year.html" class="linc">Business Quest</a></td></tr>
	<tr><td class="pl">2000</td><td class="pl"><b><a href="http://policyofliberty.net/checkout/products.php">“¿Es Realmente Nueva Zelandia el Tercer País más Libre en el Mundo?”</b></a> <i>Portada</i>, no. 59, April, pp. 14-18.</td></tr>
	<tr><td class="pl">1999</td><td class="pl"><b><a href="http://policyofliberty.net/checkout/products.php">“El Aborto y la Teoría del Fracaso del Mercado”</b></a> <i>Portada</i>, vol. 30, no. 56, December, pp. 28-32.</td></tr>
	<tr><td class="pl">1999</td><td class="pl"><b><a href="http://policyofliberty.net/checkout/products.php">“Abortion and Market Failure Theory”</b></a></td></tr>
	<tr><td class="pl">2000</td><td class="pl"><b><a href="http://policyofliberty.net/checkout/products.php">“Rape in a Free Market”</b></a></td></tr>
	<tr><td class="pl">2000</td><td class="pl"><b><a href="http://policyofliberty.net/checkout/products.php">“The Andean Altiplano: Lessons for the Mises-Tullock View of Development”</b></a></td></tr>
	<tr><td class="pl">2002</td><td class="pl"><b><a href="http://policyofliberty.net/checkout/products.php">“A Case for Evangelical Covenant Marriage”</a></b>, March</td></tr>
	<tr><td class="pl">2000</td><td class="pl"><b><a href="http://policyofliberty.net/checkout/products.php">“Faculty and Universities in a Free Market(Chile): Comment by a Fallen Free Market Academic”</b></a>, May 15</td></tr>
	<tr><td class="pl">2003</td><td class="pl"><b><a href="http://policyofliberty.net/checkout/products.php">“Bare, Beer, Baby Ruth and Blessings”</b></a> [re: Christians playing the lottery], January</td></tr>
	<tr><td class="pl">1995</td><td class="pl"><b>“The Economics of Referendum 48 for the Common Person,”</b>The Washington Institute for Policy Studies, Seattle, Wash., October</td></tr>
	<tr bgcolor="#C0C0C0"><td class="pl"></td><td class="pl"></td></tr>
</table>
<br>
<table cellpadding="0" cellspacing="0" width="771" border="0"><tr><TD bgcolor="#ffffff" colspan="4"><IMG height="3" alt="Policy of Liberty is your source for books/papers on free market economics and pro-life policy as well as quotes and links to economic related issues" align="center" src="white.gif" width="771" border="0"></TD></tr>
<TR><TD bgcolor="#99cc99"><IMG height="20" alt="Policy of Liberty is your source for books/papers on free market economics and pro-life policy as well as quotes and links to economic related issues" src="end.gif" width="360" border="0" align="center"></TD><TD bgcolor="#99cc99"><IMG height="20" alt="Policy of Liberty is your source for books/papers on free market economics and pro-life policy as well as quotes and links to economic related issues" align="center" src="backg.gif" width="27" border="0"></TD><TD bgcolor="#99cc99"><IMG height="20" alt="Policy of Liberty is your source for books/papers on free market economics and pro-life policy as well as quotes and links to economic related issues" align="center" src="bottom.gif" width="318" border="0"></TD><td bgcolor="#99cc99"><A onmouseover="changeImages('indnav_01',	 'images/indnav_01-over.gif'); return true;" onmouseout  ="changeImages('indnav_01', 'images/indnav_01.gif'); return true;" href="sindex.html"><IMG height="20" alt="Policy of Liberty en Espanol" src="images/indnav_01.gif" width="66" border="0" name="indnav_01" align="center"></A></td></TR>
<tr><TD bgcolor="#ffffff" colspan="4"><IMG height="3" alt="Policy of Liberty is your source for books/papers on free market economics and pro-life policy as well as quotes and links to economic related issues" align="center" src="white.gif" width="771" border="0"></TD></tr>
<tr><TD bgcolor="#99cc99" colspan="4" height="15" width="771"><span class="foot">&nbsp;&nbsp;&nbsp;<a href="index.php" class="foot" title="Policy of Liberty is you source for books/papers on free market economics and pro-life policy as well as quotes and links to economic related issues">home</a> &nbsp;|&nbsp; <a href="freemarket.php" class="foot" title="Free Market Textbook">free market textbook</a> &nbsp;|&nbsp; <a href="books.php" class="foot" title="Public Policy Books">public policy books</a> &nbsp;|&nbsp; <a href="papers.php" class="foot" title="Articles and Papers">articles & papers</a> &nbsp;|&nbsp; <a href="links.php" class="foot" title="Links">links</a> &nbsp;|&nbsp; <a href="quotes.php" class="foot" title="Quotes">quotes</a> &nbsp;|&nbsp; <a href="contact.php" class="foot" title="Contact Policy of Liberty">contact</a> &nbsp;|&nbsp; <a href="join.php" class="foot" title="Join Policy of Liberty">join</a> &nbsp;|&nbsp; <a href="about.php" class="foot" title="About Dr. John Cobin">about me</a></span></TD></tr></table><br></BODY></HTML>