<?define ('wwwf_IN',true);
$title = "Policy Profs for Liberty List";
$desc = "Books/papers on free market economics and policy, pro-life policy, Cobin CV, links, photos, other resources, allodial title, fire safety regulation, building regulation, free market policy, drug legalization, abortion debate";
$key = "allodial title, allodialism, allodial policy, free market textbook, homeschool books, economics books for homeschoolers, public policy and Christians, creation and evolution, Christian homeschool books, public policy books, pro-life books, abortion issue, Christians and government, building regulation, allodial title, tax protesting, revolution, fire safety regulation, accreditation of higher education, public choice economics, Virginia school, Austrian economics, law and economics, subjectivist economics, knowledge problem, market failure, government failure, urban regulation, fire safety regulation, romantic vision of government, public, choice, Austrian, economics, law, rent seeking, right, allodial, regulation, policy, vote, government, Bible, pro-life, Christian, building, zoning, liberty, planning, market, Chile, abortion debate, public school, Romans 13, feudal, privatization, allodial property";
$alt = "Policy of Liberty is your source for books/papers on free market economics and pro-life policy as well as quotes and links to economic related issues";
$titleimg = "home.jpg";include ("top.php")?>
<TABLE cellpadding="0" cellspacing="0" border="0" width="771" height="240">
<tr><td rowspan="2"><IMG height="240" alt="Policy Profs for Liberty List" src="images/numbers.jpg" width="359" border="0"></td>
<td valign="top"><p class="pl">Policy of liberty is dedicated to the advancement of liberty and responsibility in society. Its philosophy is neither strictly libertarian nor strictly conservative, though strongly supporting the former in terms of economics and the latter on most social issues, abortion in particular. POL provides resources, links, books and articles, an email list, photos and links to famous economists, great quotations for liberty.</p></td></tr>
<tr><td width="409" bgcolor="#CCCCCC" height="90" border="2" align="right"></td></tr></TABLE>
<table cellpadding="0" cellspacing="0" width="771" border="0" bgcolor="#999999">
<tr><td><img src="white.gif" height="3" width="771" alt="<? echo "$alt"?>"></td></tr>
<tr><td><p class="white"><b>Policy Profs for Liberty List:</b></p></td></TD></tr></table>
<br><table width="771"><tr><td>
<p class="head" align="center"><B>Policy Profs for Liberty List</B></p>
<br><P class="pl">Join simply by sending a blank message to join-POL@policyofliberty.net (click <A HREF="mailto:join-POL@policyofliberty.net?Subject=Subscribe&Body=subscribe%20pol-profs%0D%0A-%0D%0A%0D%0ADo not modify the contents of this email. Simply hit 'SEND' now." class="linc">here</a> to send the message now) from the email address where you want to receive list postings.</p>
<br><P class="pl">The POL list is an open forum for academic discussion of public policy issues from a classically liberal perspective.  The only rules are:
<ol><li class="pl">No spamming.</li>
<li class="pl">No flaming or nasty personal remarks. Let's keep the discussion civil please.</li>
<li class="pl">Do not send posts larger than 75k since the system will reject them.</li>
<li class="pl">No whining about too many posts. People are free to post as much as they please so long as the subject is related to BOTH (a) public policy and (b) classically liberal thought. People who do not want to read all the posts are free to use their delete key. Participants are asked to be thoughtful in using the subject line effectively and to be parsimonious when quoting previous posts.</li></ol></p>
<br><P class="pl">List subjects may be anything related to policy and classical liberalism.  Examples of some acceptable topics include, market-based regulatory alternatives, property rights, human rights (natural rights), Georgism, allodialism, abortion, theism and the "divine right of kings" doctrine, creationism/Darwinism, Austrian Economics, public choice economics, libertarian theory, anarchism, theonomy, politics and current affairs, gun control, drug laws, reviews of books and articles (or ideas for new ones), and law & economics issues.</p>
<br><P class="pl">All are welcome but the list is predominantly designed for academics, reflective lawyers, and policy professionals.  Graduate students may also enroll but are asked to maintain courteous, professional standards when they participate.</p>
<br><P class="pl">A special welcome is extended to home schoolers and Christians (or other religious folks).  The list is to be inclusive and not turn away people who have different beliefs or practices than "mainstream" classical liberals.</p>
<br><P class="pl">To post to the list, simply send your message to POL-Profs@PolicyOfLiberty.net</p>
<br><P class="pl">The list moderator and owner is <A HREF="mailto:jcobin@PolicyOfLiberty.net" class="linc">Dr. John Cobin</a>, who teaches at various Chilean universities [email: jcobin@PolicyOfLiberty.net] and the home page for Policy of Liberty and Dr. Cobin is http://www.PolicyOfLiberty.net <b>or</b> http://www.PoliticaPublica.cl</p>
<br><P class="pl"><b>Important footnote</b>: This is an active list with several dozen (about 85) subscribers from around the world. If you do not receive posts soon after subscribing, it is possible that the listserver has sent you the "welcome to POL Profs" message without actually recording your email address on the server. In that case, simply send <A HREF="mailto:jcobin@PolicyOfLiberty.net" class="linc">Dr. Cobin</a> an email with your request and he will manually subscribe you. (You might want to send a note to <A HREF="mailto:jcobin@PolicyOfLiberty.net" class="linc">Dr. Cobin</a> anyway just so he can follow-up and make sure you are subscribed.)</p></P></td></tr></table><br>
<table cellpadding="0" cellspacing="0" width="771" border="0"><? include ("base.php")?>
