<?define ('wwwf_IN',true);
$title = "Libertarianism and Rights";
$desc = "Books/papers on free market economics and policy, pro-life policy, Cobin CV, links, photos, other resources, allodial title, fire safety regulation, building regulation, free market policy, drug legalization, abortion debate";
$key = "allodial title, allodialism, allodial policy, free market textbook, homeschool books, economics books for homeschoolers, public policy and Christians, creation and evolution, Christian homeschool books, public policy books, pro-life books, abortion issue, Christians and government, building regulation, allodial title, tax protesting, revolution, fire safety regulation, accreditation of higher education, public choice economics, Virginia school, Austrian economics, law and economics, subjectivist economics, knowledge problem, market failure, government failure, urban regulation, fire safety regulation, romantic vision of government, public, choice, Austrian, economics, law, rent seeking, right, allodial, regulation, policy, vote, government, Bible, pro-life, Christian, building, zoning, liberty, planning, market, Chile, abortion debate, public school, Romans 13, feudal, privatization, allodial property";
$alt = "Policy of Liberty is your source for books/papers on free market economics and pro-life policy as well as quotes and links to economic related issues";
$titleimg = "quotes.jpg";include ("top.php")?>
<? include ("qu.php")?><br><table cellpadding="0" cellspacing="0" width="771" border="0" bgcolor="#cccccc">
<tr><td><img src="white.gif" height="3" width="771" alt="<? echo "$alt"?>"></td></tr>
<tr><td><p class="pl"><b>Libertarianism and Rights:</b></p></td></TD></tr></table>
<br><table width="771"><tr><td>
<p class="pl">
<b>“The average man's love of liberty is nine-tenths imaginary, exactly like his love of sense, justice and truth. He is not actually happy when free; he is uncomfortable, a bit alarmed, and intolerably lonely.  Liberty is not a thing for the great masses of men. It is the exclusive possession of a small and disreputable minority, like knowledge, courage and honor. It takes a special sort of man to understand and enjoy liberty—and he is usually an outlaw in democratic societies. It is, indeed, only the exceptional man who can even stand it. The average man doesn't want to be free. He simply wants to be safe.”</b>
<br>—H.L. Mencken, <i>Baltimore Evening Sun</i> (February 12, 1923).<br><br>
<b>“It is easier to commit murder than to justify it.”</b>
<br>—Papinian (Aemilius Papinianus), quoted in Barry Nicholas, An Introduction to Roman Law, p. 30 n.2 (1962).<br><br>
<b>Alternative quote to the above: “Papinian [a third-century Roman jurist, considered by many to be the greatest of Roman jurists] is said to have been put to death for refusing to compose a justification of Caracalla's murder of his brother and co-Emperor, Geta, declaring, so the story goes, that it is easier to commit murder than to justify it.”</b>
<br>—Barry Nicholas, An Introduction to Roman Law, p. 30 n.2 (1962).<br><br>
<b>“Whatever may be open to disagreement, there is one act of evil that may not, the act that no man may commit against others and no man may sanction or forgive. So long as men desire to live together, no man may initiate—do you hear me? No man may start—the use of physical force against others.”</b>
<br>—Ayn Rand, "Galt's Speech," in For the New Intellectual 164 (p. 133, paperback edition) (1961), quoted in The Ayn Rand Lexicon: Objectivism from A to Z (Harry Binswanger, ed. 1986), at 363.<br><br>
<b>“[T]he basic axiom of libertarian political theory holds that every man is a self-owner, having absolute jurisdiction over his own body. In effect, this means that no one else may justly invade, or aggress against, another's person. It follows then that each person justly owns whatever previously unowned resources he appropriates or 'mixes his labor with'. From these twin axioms— self-ownership and 'homesteading'—stem the justification for the entire system of property rights titles in a free market society.”</b>
<br>—Murray N. Rothbard, "Law, Property Rights, and Air Pollution," Cato Journal, Vol. 2 (1982): 60-61.<br><br>
<b>“[O]ur existence is due to the fact that we do not, indeed cannot accept a norm outlawing property in other scarce resources next to and in addition to that of one's physical body. Hence, the right to acquire such goods must be assumed to exist.”</b>
<br>—Hans-Hermann Hoppe, The Economics and Ethics of Private Property: Studies in Political Economy and Philosophy (Kluwer: 1993): 185.<br><br>
<b>Old saying: “What you do speaks so loud I can't hear what you are saying.”</b>
<br>—Quoted in Clarence Carson, "Free Enterprise: The Key to Prosperity", in The Freedom Philosophy Vol. 27, 27 (1988).<br><br>
<b>“[T]he various values defended by liberalism are not arbitrary, a matter of mere personal  preference, nor do they derive from some natural law . . . . Rather, they are nothing less and nothing more than what could be called the operative presuppositions or intrinsic features and demands of communicative rationality itself. In other words, they are values that are implicitly recognized and affirmed by everyone by the very fact of their engaging in communicative reason. This amounts to saying that no one can rationally deny them without at the same time denying reason, without self-contradiction, without in fact abandoning all attempts to persuade the other and to reach agreement. . . . [T]he notion of universal human rights and liberties is not an . . . arbitrary value, a matter of mere personal preference . . . . On the contrary, it is nothing less and nothing more than the operative presupposition or intrinsic feature and demand of communicative rationality itself.”</b>
<br>—G.B. Madison, The Logic of Liberty (New York: Greenwood Press, 1986): 266, 269.<br><br>
<b>“The only proof that can be offered for the validity of the liberal position is that we are discussing it and its acceptance is a presupposition of discussion, since discussion is the essence of the position itself.”</b>
<br>—Frank H. Knight, Freedom and Reform (Indianapolis: Liberty Press, 1982): 473=9674.<br><br>
<b>“[J]ust as one cannot win a game of chess against an opponent who will not make any moves—and just as one cannot argue mathematically with a person who will not commit himself to any mathematical statements—so moral argument is impossible with a man who will make no moral judgements at all . . . . Such a person is not entering the arena of moral dispute, and therefore it is impossible to contest with him. He is compelled also—and this is important—to abjure the protection of morality for his own interests.”</b>
<br>—R.M. Hare, Freedom and Reason (1963): A7 6.6<br><br>
<b>“[T]he victim is entitled to respond according to the rule ('The use of force is permissible') that the aggressor himself has implicitly laid down.”</b>
<br>—John Hospers, "Retribution: The Ethics of Punishment," in Assessing the Criminal: Restitution, Retribution, and the Legal Process, Randy E. Barnett and John Hagel III, eds., (Cambridge: Ballinger, 1977): p. 191.<br><br>
<b>“The injury [the penalty] which falls on the criminal is not merely implicitly just—as just, it is eo ipso his implicit will, an embodiment of his freedom, his right; on the contrary, it is also a right established within the criminal himself, i.e., in his objectively embodied will, in his action. The reason for this is that his action is the action of a rational being and this implies that it is something universal and that by doing it the criminal has laid down a law which he has explicitly recognized in his action and under which in consequence he should be brought as under his right.”</b>
<br>—G.W.F. Hegel, The Philosophy of Right A7 100 (T.M. Knox trans., 1969) (reprinted in Philosophical Perspectives on Punishment (Gertrude Ezorsky ed., 1972): 107 (Emphasis in last sentence added; brackets in Ezorsky)<br><br>
<b>“With him [an aggressor] we are returned to the first-stage state of nature and may use force against him. In so doing we do not violate his rights or in any other way violate the principle of right, because he has broken the reciprocity required for us to view such a principle [of rights] as binding. In this we find the philosophic grounding for the moral legitimacy of the practice of punishment. Punishment is just that practice which raises the price of violation of the principle of right so as to give us all good reason to accept that principle.”</b>
<br>—J. Charles King, A Rationale for Punishment, 4 J. Libertarian Stud. (1980): 154.<br><br>
<b>“In transgressing the law of Nature, the offender declares himself to live by another rule than that of reason and common equity . . . and so he becomes dangerous to mankind; . . . every man . . . by the right he hath to preserve mankind in general, may restrain, or where it is necessary, destroy things noxious to them, and so may bring such evil on any one who hath transgressed that law, as may make him repent of the doing of it . . . ." B6 11: A murderer "hath, by the unjust violence and slaughter he hath committed upon one, declared war against all mankind, and therefore may be destroyed as a lion or a tiger, one of those wild savage beasts with whom men can have no society nor security."; "It has been noted that one who wishes to extinguish or convey an inalienable right may do so by committing the appropriate wrongful act and thereby forfeiting it.”</b>
<br>—John Locke, The Second Treatise on Civil Government B6 8<br><br>
<b>“[W]hen someone is punished for having violated others' rights, it is not the case that the criminal has alienated or otherwise lost his rights; rather, it is the case that the criminal's choice to live in a rights-violating way is being respected.”</b>
<br>—Douglas B. Rasmussen &amp; Douglas J. Den Uyl, Liberty and Nature: An Aristotelian Defense of Liberal Order (1991): 85<br><br>
<b>“[I]f someone attacks another, that act carries with it, as a matter of the logic of aggression, the implication that from a rational moral standpoint the victim may, and often should retaliate.”</b>
<br>—Tibor R. Machan, Individuals and Their Rights (1989): 176<br><br>
<b>“[T]hose who do not want peace, or want it only for others in relation to themselves rather than vice versa, are on their own and may in principle be dealt with by any degree of violence we like.”</b>
<br>—Jan Narveson, The Libertarian Idea (1988): 210<br><br>
<b>“What we cannot speak about we must pass over in silence.”</b>
<br>—Ludwig Wittgenstein, Tractatus Logico-Philosophicus, (D.F. Pears &amp; B.F. McGuinness trans., London &amp; New York: Routledge, 1961): ¶ 7.0 (p. 74).<br><br>
<b>“The socialist society would have to forbid capitalist acts between consenting adults.”</b>
<br>—Robert Nozick, Anarchy, State, and Utopia (1974), p. 163.<br><br>
<b>“But when mankind increased in number, craft, and ambition, it became necessary to entertain conceptions of more permanent dominion; and to appropriate to individuals not the immediate use only, but the very substance of the thing to be used. Otherwise innumerable tumults must have arisen, and the good order of the world been continually broken and disturbed, while a variety of persons were striving to get the first occupation of the same thing, or disputing which of them had actually gained it. As human life also grew more and more refined, abundance of conveniences were devised to render it more easy, commodious, and agreeable; as, habitations for shelter and safety, and raiment for warmth and decency. But no man would be at the trouble to provide either, so long as he had only an usufructuary property in them, which was to cease the instant that he quitted possession; if, as soon as he walked out of his tent, or pulled off his garment, the next stranger who came by would have aright to inhabit the one, and to wear the other.”</b>
<br>—2 William Blackstone, Commentaries on the Laws of England (last emphasis added): *4.<br><br>
<b>“The right to enjoy property without lawful deprivation . . . is in truth a personal right . . . . In fact, a fundamental interdependence exists between the personal right to liberty and the personal right in property. Neither could have meaning without the other. That rights in property are basic civil rights has long been recognized.”</b>
<br>—United States Supreme Court, Lynch v. Household Fin. Corp., 405 U.S. 538, 552 (1972).<br><br>
<b>“When we say that one has the right to do certain things we mean this and only this, that it would be immoral for another, alone or in combination, to stop him from doing this by the use of physical force or the threat thereof. We do not mean that any use a man makes of his property within the limits set forth is necessarily a moral use.”</b>
<br>—James A. Sadowsky, "Private Property and Collective Ownership," in The Libertarian Alternative, ed. Tibor R. Machan (Chicago: Nelson-Hall Co., 1974), 120=9621.<br><br>
<b>“[L]ife for life, eye for eye, tooth for tooth, hand for hand, foot for foot, burn for burn, wound for wound, stroke for stroke.”</b>
<br>—Exodus 21:23-25, in God, The Jerusalem Bible: Reader's Edition (1968). See also Deuteronomy 19:21; Leviticus 24:17-21.<br><br>
<b>“Having once the right to punish, we may modify the punishment according to the useful and the pleasant.”</b>
<br>—F.H. Bradley, Ethical Studies (2d ed. 1927): 26-27.<br><br>
<b>“[W]e must distinguish two questions commonly confused. They are, first Why do men in fact punish? This is a question of fact to which there may be many different answers . . . . The second question, to be carefully distinguished from the first, is What justifies men in punishing? Why is it morally good or morally permissible for them to punish?”</b>
<br>—H.L.A. Hart, Punishment and Responsibility (1968): 74.” <br><br>
<b>“[T]here is no affront [or injustice] where the victim consents.”</b>
<br>—[Roman jurist] Ulpian (Domitius Ulpianus), Edict, book 56, 4 The Digest of Justinian (Theodor Mommsen, Paul Krueger &amp; Alan Watson eds., 1985), at Book 47, A7 10.1.5 (nulla iniuria est, quae in volentem fiat).<br><br>
<b>“The case for the recognition of consent as a defense in case of the deliberate infliction of harm can also be made in simple and direct terms. The self-infliction of harm generates no cause of action, no matter why inflicted. There is no reason, then, why a person who may inflict harm upon himself should not, prima facie, be allowed to have someone else do it for him.”</b>
<br>—Richard A. Epstein, Intentional Harms, J. Legal Stud. 4 (1975): 411.<br><br>
<b>“When men are judges in their own cases, it can be objected that "self-love will make men partial to themselves and their friends; and, on the other side, ill-nature, passion, and revenge will carry them too far in punishing others . . . .”</b>
<br>—John Locke, The Second Treatise on Civil Government at 13 (B6 11)</p></td></tr></table><br>
<table cellpadding="0" cellspacing="0" width="771" border="0"><? include ("base.php")?>
