<?define ('wwwf_IN',true);
$title = "Law & Politics";
$desc = "Books/papers on free market economics and policy, pro-life policy, Cobin CV, links, photos, other resources, allodial title, fire safety regulation, building regulation, free market policy, drug legalization, abortion debate";
$key = "allodial title, allodialism, allodial policy, free market textbook, homeschool books, economics books for homeschoolers, public policy and Christians, creation and evolution, Christian homeschool books, public policy books, pro-life books, abortion issue, Christians and government, building regulation, allodial title, tax protesting, revolution, fire safety regulation, accreditation of higher education, public choice economics, Virginia school, Austrian economics, law and economics, subjectivist economics, knowledge problem, market failure, government failure, urban regulation, fire safety regulation, romantic vision of government, public, choice, Austrian, economics, law, rent seeking, right, allodial, regulation, policy, vote, government, Bible, pro-life, Christian, building, zoning, liberty, planning, market, Chile, abortion debate, public school, Romans 13, feudal, privatization, allodial property";
$alt = "Policy of Liberty is your source for books/papers on free market economics and pro-life policy as well as quotes and links to economic related issues";
$titleimg = "quotes.jpg";include ("top.php")?>
<? include ("qu.php")?><br><table cellpadding="0" cellspacing="0" width="771" border="0" bgcolor="#cccccc">
<tr><td><img src="white.gif" height="3" width="771" alt="<? echo "$alt"?>"></td></tr>
<tr><td><p class="pl"><b>Law & Politics:</b></p></td></TD></tr></table>
<br><table width="771"><tr><td>
<p class="pl"><b>“[I]t is perfectly possible, in theory and historically, to have efficient and courteous police, competent and learned judges, and a body of systematic and socially accepted law—and none of these things being furnished by a coercive government.”</b>
<br>—Murray N. Rothbard, For A New Liberty: The Libertarian Manifesto (reprint ed. 1985): 234.”<br><br>
<b>“[Jeremy Bentham] evinced no misgivings about the power or reason—in particular Bentham's reason—to decide any questions of policy de novo, without benefit of authority, consensus, precedent, etc. . . . Bentham is not a little the fanatic whose willingness to sweep aside the obstacles to implementation of his proposals draws sustenance from a boundless confidence in his own reasoning powers. . . . Bentham's blind spot about the problem of social order is of a piece with his enthusiasm for social planning. He worried about all monopolies except the most dangerous, the monopoly of political power.”</b>
<br>—Richard A. Posner, "Blackstone and Bentham," Journal of Law &amp; Economics. 19 (1976): 594, 603-606<br><br>
<b>“The Nazi party was elected to office by the freely cast ballots of millions of German voters . . . . In the national election of July 1932, the Nazis obtained 37 percent of the vote and a plurality of seats in the Reichstag. On January 30, 1933, in full accordance with the country's legal and constitutional principles, Hitler was appointed Chancellor. Five weeks later, in the last (and semi-free) election of the pre-totalitarian period, the Nazis obtained 17 million votes, 44 percent of the total.”...[new paragraph]...The voters were aware of the Nazi ideology. Nazi literature, including statements of the Nazi plans for the future, papered the country during the last years of the Weimar Republic. Mein Kampf alone sold more than 200,000 copies between 1925 and 1932. The essence of the political system which Hitler intended to establish in Germany was clear.”</b>
<br>—Leonard Peikoff, The Ominous Parallels: The End of Freedom in America (1982): 5-6.<br><br>
<b>“No socialist author ever gave a thought to the possibility that the abstract entity which he wants to vest with unlimited power—whether it is called humanity, society, nation, state, or government—could act in a way of which he himself disapproves.”</b>
<br>—Ludwig von Mises, Human Action: A Treatise on Economics, 692 (rev'd ed. 1966)<br><br>
<b>“[T]he ballot . . . is a mere substitute for a bullet.”</b>
<br>—Lysander Spooner, No Treason No. VI: The Constitution of No Authority at 15, in No Treason: The Constitution of No Authority and A Letter to Thomas F. Bayard (Ralph Myles Publisher ed n 1973) (1870); also reprinted in The Lysander Spooner Reader (1992): 71.<br><br>
<b>“For the law of Nature would, as all other laws that concern men in this world, be in vain if there were nobody that in the state of Nature had a power to execute that law, and thereby preserve the innocent and restrain offenders . . . .”</b>
<br>—John Locke, The Second Treatise on Civil Government (Prometheus Books ed n 1986) (1690), at B6 7.</p></td></tr></table><br>
<table cellpadding="0" cellspacing="0" width="771" border="0"><? include ("base.php")?>
