<?define ('wwwf_IN',true);
$title = "Property: rights, lands, allodialism, etc. plus Georgism, fascism, communism...";
$desc = "Books/papers on free market economics and policy, pro-life policy, Cobin CV, links, photos, other resources, allodial title, fire safety regulation, building regulation, free market policy, drug legalization, abortion debate";
$key = "allodial title, allodialism, allodial policy, free market textbook, homeschool books, economics books for homeschoolers, public policy and Christians, creation and evolution, Christian homeschool books, public policy books, pro-life books, abortion issue, Christians and government, building regulation, allodial title, tax protesting, revolution, fire safety regulation, accreditation of higher education, public choice economics, Virginia school, Austrian economics, law and economics, subjectivist economics, knowledge problem, market failure, government failure, urban regulation, fire safety regulation, romantic vision of government, public, choice, Austrian, economics, law, rent seeking, right, allodial, regulation, policy, vote, government, Bible, pro-life, Christian, building, zoning, liberty, planning, market, Chile, abortion debate, public school, Romans 13, feudal, privatization, allodial property";
$alt = "Policy of Liberty is your source for books/papers on free market economics and pro-life policy as well as quotes and links to economic related issues";
$titleimg = "quotes.jpg";include ("top.php")?>
<? include ("qu.php")?><br><table cellpadding="0" cellspacing="0" width="771" border="0" bgcolor="#cccccc">
<tr><td><img src="white.gif" height="3" width="771" alt="<? echo "$alt"?>"></td></tr>
<tr><td><p class="pl"><b>Property: rights, lands, allodialism, etc. plus Georgism, fascism, communism...:</b></p></td></TD></tr></table>
<br><table width="771"><tr><td><p class="pl"><b>“Hitler did not have Mussolini's revolutionary socialist background...Nevertheless, he shared the socialist hatred and contempt for the 'bourgeoisie' and 'capitalism' and exploited for his purposes the powerful socialist traditions of Germany. The adjectives 'socialist' and 'worker' in the official name of Hitler's party ('The Nationalist-Socialist German Workers' Party') had not merely propagandistic value...On one occassion, in the midst of World war II, Hitler even declared that 'basically National Socialism and Marxism are the same.'”</b>
<br>—Richard Pipes (1999), Property and Freedom, New York: Alfred A. Knopf, p. 220
<br><br><b>“...the Domesday Book, the cadastre of English landed properties compiled under William the Conqueror, probably used the terms "feodum" (conditional tenure) and "alodium" (outright property) as equivalents to mean 'a heritable estate, as absolute an ownership of land as is conceivable'.”</b>
<br>—Richard Pipes (1999), Property and Freedom, New York: Alfred A. Knopf, p. 106 [Note from Dr. Cobin: While I doubt that this notion of Pipes is true, if for no other reason than that the English above all Europeans knew the meaning of absolute land rights and there is a stark difference between the two words, but then we might also consider the following quotation:]
<br><br><b>“At the time of the Norman Conquest the landed estates of the English royalty stood at their zenith. The conquerors abolished allodial holdings: previous owners, if permitted to keep their estates, became royal tenants in chief. Normal royalty not only inherited the holdings of the deposed Anglo-Saxon kings but also the confiscated real properties from the lords who had offered them resistance, much of which the distributed among their tenants. The tenants in chief were required to provide the king with fixed quotas of cavalry. To ensure that they had the required number of horsemen, they, in turn, granted estates to knights. Thus the feudal chain was forged. But William the Conqueror assumed that all the land, secular as well as clerical, belonged to him and was held by his tenants on feudal terms. A tenant in chief who failed in his duties forfeited his lands to the crown.”</b>
<br>—Richard Pipes (1999), Property and Freedom, New York: Alfred A. Knopf, p. 126 [Note from Dr. Cobin: This statement by Pipes seems to contradict the one above. This one suggests that the people knew what allodium was and the conquering king abolished it in favor of setting up a feudal system.]
<br><br><b>“Votchina land, whether donated by the prince for services rendered, inherited, or purchased, was allodial property: accords between the appanage [a term originally meaning land set aside for the upkeep of children] princes commonly contained a formula guaranteeing every every noble possession of his estate even if he did not serve the prince on whose territory it was located...The process of transforming allodial property into tenure conditional on state service began in earnest in the reign of Ivan III at the end of the fifteenth century...”</b>
<br>—Richard Pipes (1999), Property and Freedom, New York: Alfred A. Knopf, pp. 168-169
<br><br><b>“As can be seen, the evolution in Russia of property in land ran in the diametrically opposite direction from the rest of Europe. At the time when Western Europe knew mainly conditional land tenure in the form of fiefs, Russia knew only allodial property. By the time conditional tenure in Western Europe yielded to outright ownership, in Russia allodial holding turned into royal fiefs and their onetime owners became the ruler's tenants in chief. No single factor in Russia's history explains better the divergence of her political and economic evolution from that of the rest of Western Europe, because it meant that in the age of absolutism in Russia, unlike most of Western Europe, property presented no barrier to royal power.”</b>
<br>—Richard Pipes (1999), Property and Freedom, New York: Alfred A. Knopf, p. 180
<br><br><span class="red">Note from Dr. Cobin: Leaving aside the flawed idea that Western Europeans enjoyed "outright ownership" (which Pipes himself seemed to contradict in the third chapter of his book), evidently, the fall of Russia to the Mongols (Genghis Khan and his son) ruined property rights in Russia, but in some places, notably the ancient Viking settlement of Novgorod (about 100 miles south-southeast of modern St. Petersburg), allodial property and liberty flourished. (It was too far north for Genghis Khan or his son's army to bother with evidently.) Pskov, near the borders of modern Latvia and Estonia, was another Russian city with similar circumstances, but not nearly as bright as Novgorod. Pipe's account of Novgorod is an important finding for real property theory and policy. It could suggest yet another example where allodialism fostered liberty naturally. Novgorod had the last and longest standing parliament in Russia, and had the best checks on princely power. Its best days occurred during the period 1200 to 1450 or a little later maybe, until it was ruined by Ivan the Terrible. As an aside, apparently allodial policy did not provide sufficient defense services given that it fell to Ivan. In Russia, "serfdom was eternal". (p. 183). The Tsar owned everything (as the sole allodiary) and there were not any nobles who held land as they did in England. No one wanted to produce and store anything for fear tht the Prince would confiscate it by force. What little the people did have was often hidden in forests or other secluded places. There was, in a word, economic death in Russia which persisted at least until 1991. At any rate, it seems that one could note Novgorod, in addition to pre norman England, as places where allodial policy flourished. There are also other paces where allodial thnking had some significant footing, perhaps Poland and Iceland and even medieval France (although I have seen little evidence from them other than a stray passage in a history text here or there), as well as the ante-bellum USA See my book dealing with allodial policy.</span>
<br><br><p class="pl"><b>“Russia's experience indicates that freedom cannot be legislated: it has to grow gradually, in close association with property and law. For while acquisitiveness is natural, respect for the property--and the liberty--of others is not. It has to be inculcated until it sinks such deep roots in the people's consciousness that it is able to withstand all efforts to crush it.”</b>
<br>—Richard Pipes (1999), Property and Freedom, New York: Alfred A. Knopf, p. 208
<br><br><b>And some apropos words from the enemies of freedom…</b>
<br><br><b>“Democracy is not so much a form of government as a set of principles.”</b>
<br>—Woodrow Wilson
<br><br><b>“Liberty has never come from the government. Liberty has always come from the subjects of it. The history of liberty is a history of resistance.”</b>
<br>—Woodrow Wilson
<br><br><b>“A nation which does not remember what it was yesterday, does not know what it is today, nor what it is trying to do. We are trying to do a futile thing if we do not know where we came from or what we have been about.”</b>
<br>—Woodrow Wilson
<br><br><b>“Democracy, the practice of self-government, is a covenant among free men to respect the rights and liberties of their fellows.”</b>
<br>—Franklin D. Roosevelt
<br><br><b>“For the bureaucrat, the world is a mere object to be manipulated by him.”</b>
<br>—Karl Marx</p></td></tr></table><br>
<table cellpadding="0" cellspacing="0" width="771" border="0"><? include ("base.php")?>
