<?define ('wwwf_IN',true);
$title = "Economics";
$desc = "Books/papers on free market economics and policy, pro-life policy, Cobin CV, links, photos, other resources, allodial title, fire safety regulation, building regulation, free market policy, drug legalization, abortion debate";
$key = "allodial title, allodialism, allodial policy, free market textbook, homeschool books, economics books for homeschoolers, public policy and Christians, creation and evolution, Christian homeschool books, public policy books, pro-life books, abortion issue, Christians and government, building regulation, allodial title, tax protesting, revolution, fire safety regulation, accreditation of higher education, public choice economics, Virginia school, Austrian economics, law and economics, subjectivist economics, knowledge problem, market failure, government failure, urban regulation, fire safety regulation, romantic vision of government, public, choice, Austrian, economics, law, rent seeking, right, allodial, regulation, policy, vote, government, Bible, pro-life, Christian, building, zoning, liberty, planning, market, Chile, abortion debate, public school, Romans 13, feudal, privatization, allodial property";
$alt = "Policy of Liberty is your source for books/papers on free market economics and pro-life policy as well as quotes and links to economic related issues";
$titleimg = "quotes.jpg";include ("top.php")?>
<? include ("qu.php")?><br><table cellpadding="0" cellspacing="0" width="771" border="0" bgcolor="#cccccc">
<tr><td><img src="white.gif" height="3" width="771" alt="<? echo "$alt"?>"></td></tr>
<tr><td><p class="pl"><b>Economics:</b></p></td></TD></tr></table>
<br><table width="771"><tr><td>
<p class="pl"><b>“Less than seventy-five years after it officially began, the contest between capitalism and socialism is over: capitalism has won.”</b>
<br>—Robert Heilbroner (1989), "The Triumph of Capitalism", The New Yorker, January 23: p. 98 <br><br>
<b>“Where there is no market there is no price system, and where there is no price system there can be no economic calculation.”</b>
<br>—Mises, Socialism: An Economic and Sociological Analysis (Liberty Fund rev'd ed., trans. J. Kahane 1981): 113 (p. 131 of the 1936 J. Kahane translation).<br><br>
<b>“The paradox of planning is that it cannot plan, because of the absence of economic calculation. What is called a planned economy is no economy at all.”</b>
<br>—Ludwig von Mises, Human Action: A Treatise on Economics, p. 700.<br><br>
<b>“If we were to renounce monetary calculation, every economic computation would become absolutely impossible. . . . [The socialist society] must forgo the intellectual division of labor that consists in the cooperation of all entrepreneurs, landowners, and workers as producers and consumers in the formation of market prices. But without it, rationality, i.e., the possibility of economic calculation, is unthinkable.”</b>
<br>—Ludwig von Mises, Liberalism: In the Classical Tradition (trans. Ralph Raico, ed n 1985): 75.<br><br>
<b>“Mises demonstrated that, in any economy more complex than the Crusoe or primitive family level, the socialist planning board would simply not know what to do, or how to answer any of these vital questions. Developing the momentous concept of calculation, Mises pointed out that the planning board could not answer these questions because socialism would lack the indispensable tool that private entrepreneurs use to appraise and calculate: the existence of a market in the means of production, a market that brings about money prices based on genuine profit-seeking exchanges by private owners of these means of production. Since the very essence of socialism is collective ownership of the means of production, the planning board would not be able to plan, or to make any sort of rational economic decisions. Its decisions would necessarily be completely arbitrary and chaotic, and therefore the existence of a socialist planned economy is literally 'impossible' (to use a term long ridiculed by Mises's critics).”</b>
<br>—Murray N. Rothbard, "The End of Socialism and the Calculation Debate Revisited", Rev. Austrian Econ. 5 (1991): 52-53.<br><br>
<b>“It is . . . paradoxical that the very economists who support the free market at the present time do not seem to care to consider whether a free market could really last within a legal system centered on legislation.”</b>
<br>—Bruno Leoni, Freedom and the Law (Liberty Fund expanded . ed., Indianapolis: Liberty Fund, 1991) (1961): 23.<br><br>
<b>“[In a system where legislation is widely used to "make" law,] nobody can tell whether a rule may be only one year or one month or one day old when it will be abrogated by a new rule. All these rules are precisely worded in written formulae that readers or interpreters cannot change at their will. Nevertheless, all of them may go as soon and as abruptly as they came. The result is that, if we leave out of the picture the ambiguities of the text, We are always "certain" as far as the literal content of each rule is concerned at any given moment, But we are never certain that tomorrow we shall still have the rules we have today.”</b>
<br>—Bruno Leoni, Freedom and the Law (Liberty Fund expanded . ed., Indianapolis: Liberty Fund, 1991) (1961): 74-75.<br><br>
<b>“The legal system centered on legislation, while involving the possibility that other people (the legislators) may interfere with our actions every day, also involves the possibility that they may change their way of interfering every day. As a result, people are prevented not only from freely deciding what to do, but from foreseeing the legal effects of their daily behavior.”</b>
<br>—Bruno Leoni, Freedom and the Law (Liberty Fund expanded. ed., Indianapolis: Liberty Fund, 1991) (1961): 10.<br><br>
<b>“In a decentralized legal system, "[l]aw develops in a case by case manner during which judges fit and adapt existing law to circumstances so as to produce an overall order which, although it may not be efficient in a technical, rationalistic sense, . . . is more stable than that created by statute . . . . [S]tatute law is in fact much more capricious [than common law] precisely because, in the modern world especially, statutes change frequently according to the whims of legislatures . . . . A structure of law which is not the result of will and cannot be known in its entirety, paradoxically, displays more regularities than a written code.”</b>
<br>—Barry, The Tradition of Spontaneous Order, 5 Lit. of Liberty 7, 44 (1982), quoted in Peter H. Aranson, "Bruno Leoni in Retrospect," 11 Harv. J. Law &amp; Publ. Policy (1988): at 723, n.40.<br><br>
<b>“Mass fabrication of laws ends by jeopardizing the other fundamental requisite of law—certainty.”</b>
<br>—Giovanni Sartori, Liberty and Law (1976): p. 38.<br><br>
<b>“[T]he mere fact of legislation—of democratic law-making—increases the degree of uncertainty. Rather than being immutable and hence predictable, law becomes increasingly flexible and unpredictable. What is right and wrong today may not be so tomorrow. The future is thus rendered more haphazard. Consequently, all around time preferences degrees will rise, consumption and short-term orientation will be stimulated, and at the same time the respect for all laws will be systematically undermined and crime promoted (for if there is no immutable standard of right , then there is also no firm definition of crime ).”</b>
<br>—Hans-Hermann Hoppe, "Time Preference, Government, and the Process of De-Civilization from Monarchy to Democracy," 5 J. des Economistes et des Etudes Humaines (1994): 340.<br><br>
<b>“Without legislative interference by non-judges, the "common law would grow gradually. It would grow and develop in the same way that all customary law grows and develops, particularly as a consequence of the mutual consent of parties entering into reciprocal arrangements. For example, two parties may enter into a contract, but something then occurs that the contract did not clearly account for. The parties agree to call upon an arbitrator or mediator to help lead them to a solution. The solution affects only those parties in the dispute, but if it turns out to be effective and the same potential conflict arises again, it may be voluntarily adopted by others. In this way, the solution becomes part of customary law.”</b>
<br>—Bruce L. Benson,   The Enterprise of Law: Justice Without the State (1990), at 283 (endnote omitted).<br><br>
<b>“Great part of that order which reigns among mankind is not the effect of Government. It has its origin in the principles of society and the natural constitution of man. It existed prior to Government, and would exist if the formality of Government was abolished. The mutual dependence and reciprocal interest which man has upon man, and all the parts of a civilised community upon each other, create that great chain of connection which holds it together. The landholder, the farmer, the manufacturer, the merchant, the tradesman, and every occupation, prospers by the aid which each receives from the other, and from the whole. Common interest regulates their concerns, and forms their law; and the laws which common usage ordains, have a greater influence than the laws of Government. In fine, society performs for itself almost everything which is ascribed to Government.”</b>
<br>—Thomas Paine, "The Rights of Man" (Part II, Chapter 1, "Of Society and Civilisation"), in Common Sense, The Rights of Man, and Other Essential Writings of Thomas Paine, (Meridian 1984) (1792), at 228.<br><br>
<b>“For it is an established rule to abide by former precedents, where the same points come again in litigation: as well to keep the scale of justice even and steady, and not liable to waver with every new judge's opinion; as also because the law in that case being solemnly declared and determined, what before was uncertain, and perhaps indifferent, is now become a permanent rule, which it is not in the breast of any subsequent judge to alter or vary from, according to his private sentiments . . . .”</b>
<br>—1 William Blackstone, Commentaries on the Laws of England: A7 83, at *69<br><br>
<b>“[W]hen laws are to be framed by popular assemblies, even of the representative kind, it is too Herculean a task to begin the work of legislation afresh, and extract a new system from the discordant opinions of more than five hundred counselors. A single legislator or an enterprising sovereign, a Solon or Lycurgus, a Justinian or a Frederick, may at any time form a concise, and perhaps an uniform, plan of justice; and evil betide that presumptuous subject who questions its wisdom or utility. But who that is acquainted with the difficulty of new-modeling any branch of our statute laws (though relating but to roads or to parish settlements) will conceive it ever feasible to alter any fundamental point of the common law, with all its appendages and consequents, and set up another rule in its stead?”</b>
<br>—3 William Blackstone, Commentaries on the Laws of England: *267</p></td></tr></table><br>
<table cellpadding="0" cellspacing="0" width="771" border="0"><? include ("base.php")?>
